# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

{ lib, nodejs, stdenv, fetchurl, writeText, git, cacert }:
{ src, overrideAttrs ? null, ... } @ args:

let

  yarnPath = ./.yarn/releases/yarn-3.2.4.cjs;
  lockfile = ./yarn.lock;
  cacheFolder = ".yarn/cache";

  # Call overrideAttrs on a derivation if a function is provided.
  optionalOverride = fn: drv:
    if fn == null then drv else drv.overrideAttrs fn;

  # Common attributes between Yarn derivations.
  drvCommon = {
    # Make sure the build uses the right Node.js version everywhere.
    buildInputs = [ nodejs ];
    # Tell node-gyp to use the provided Node.js headers for native code builds.
    npm_config_nodedir = nodejs;
    # Tell node-pre-gyp to never fetch binaries / always build from source.
    npm_config_build_from_source = "true";
    # Defines the shell alias to run Yarn.
    postHook = ''
      yarn() {
        CI=1 node "${yarnPath}" "$@"
      }
    '';
  };

  # Create derivations for fetching dependencies.
  cacheDrvs = let
    builder = builtins.toFile "builder.sh" ''
      source $stdenv/setup
      cd "$src"
      HOME="$TMP" yarn_cache_folder="$TMP" CI=1 \
        node '${yarnPath}' nixify fetch-one $locator
      # Because we change the cache dir, Yarn may generate a different name.
      mv "$TMP/$(sed 's/-[^-]*\.[^-]*$//' <<< "$outputFilename")"-* $out
    '';
  in lib.mapAttrs (locator: { filename, sha512 }: stdenv.mkDerivation {
    inherit src builder locator;
    name = lib.strings.sanitizeDerivationName locator;
    buildInputs = [ nodejs git cacert ];
    outputFilename = filename;
    outputHashMode = "flat";
    outputHashAlgo = "sha512";
    outputHash = sha512;
  }) cacheEntries;

  # Create a shell snippet to copy dependencies from a list of derivations.
  mkCacheBuilderForDrvs = drvs:
    writeText "collect-cache.sh" (lib.concatMapStrings (drv: ''
      cp ${drv} '${drv.outputFilename}'
    '') drvs);


  # Main project derivation.
  project = stdenv.mkDerivation (drvCommon // {
    inherit src;
    name = "@denotarius/denotarius-api";
    # Disable Nixify plugin to save on some unnecessary processing.
    yarn_enable_nixify = "false";

    configurePhase = ''
      # Copy over the Yarn cache.
      rm -fr '${cacheFolder}'
      mkdir -p '${cacheFolder}'
      pushd '${cacheFolder}' > /dev/null
      source ${mkCacheBuilderForDrvs (lib.attrValues cacheDrvs)}
      popd > /dev/null

      # Yarn may need a writable home directory.
      export yarn_global_folder="$TMP"

      # Some node-gyp calls may call out to npm, which could fail due to an
      # read-only home dir.
      export HOME="$TMP"

      # running preConfigure after the cache is populated allows for
      # preConfigure to contain substituteInPlace for dependencies as well as the
      # main project. This is necessary for native bindings that maybe have
      # hardcoded values.
      runHook preConfigure



      # Run normal Yarn install to complete dependency installation.
      yarn install --immutable --immutable-cache

      runHook postConfigure
    '';

    buildPhase = ''
      runHook preBuild
      runHook postBuild
    '';

    installPhase = ''
      runHook preInstall

      mkdir -p $out/libexec $out/bin

      # Move the entire project to the output directory.
      mv $PWD "$out/libexec/$sourceRoot"
      cd "$out/libexec/$sourceRoot"

      # Invoke a plugin internal command to setup binaries.
      yarn nixify install-bin $out/bin

      runHook postInstall
    '';

    passthru = {
      inherit nodejs;
    };
  });

cacheEntries = {
"@types/uuid@npm:8.3.4" = { filename = "@types-uuid-npm-8.3.4-7547f4402c-6f11f3ff70.zip"; sha512 = "6f11f3ff70f30210edaa8071422d405e9c1d4e53abbe50fdce365150d3c698fe7bbff65c1e71ae080cbfb8fded860dbb5e174da96fdbbdfcaa3fb3daa474d20f"; };
"ansi-colors@npm:4.1.3" = { filename = "ansi-colors-npm-4.1.3-8ffd0ae6c7-a9c2ec8420.zip"; sha512 = "a9c2ec842038a1fabc7db9ece7d3177e2fe1c5dc6f0c51ecfbf5f39911427b89c00b5dc6b8bd95f82a26e9b16aaae2e83d45f060e98070ce4d1333038edceb0e"; };
"eslint-config-prettier@npm:8.5.0" = { filename = "eslint-config-prettier-npm-8.5.0-a1dd58b6d8-0d0f5c32e7.zip"; sha512 = "0d0f5c32e7a0ad91249467ce71ca92394ccd343178277d318baf32063b79ea90216f4c81d1065d60f96366fdc60f151d4d68ae7811a58bd37228b84c2083f893"; };
"eslint-plugin-promise@npm:6.0.1" = { filename = "eslint-plugin-promise-npm-6.0.1-44f44fa21c-c1bb3c2e59.zip"; sha512 = "c1bb3c2e591787e97133dcaf764f908420a3a1959a3132e199db8f14d70dfa79fc9caf991ca60a4b60ae5f1f9823bc96c2e52304828a4278ef2f3964fe121de9"; };
"prettier@npm:2.7.1" = { filename = "prettier-npm-2.7.1-d1f40f5e1a-55a4409182.zip"; sha512 = "55a4409182260866ab31284d929b3cb961e5fdb91fe0d2e099dac92eaecec890f36e524b4c19e6ceae839c99c6d7195817579cdffc8e2c80da0cb794463a748b"; };
"uuid@npm:9.0.0" = { filename = "uuid-npm-9.0.0-46c41e3e43-8dd2c83c43.zip"; sha512 = "8dd2c83c43ddc7e1c71e36b60aea40030a6505139af6bee0f382ebcd1a56f6cd3028f7f06ffb07f8cf6ced320b76aea275284b224b002b289f89fe89c389b028"; };
"typescript@npm:4.7.4" = { filename = "typescript-npm-4.7.4-65aa6ffb42-5750181b1c.zip"; sha512 = "5750181b1cd7e6482c4195825547e70f944114fb47e58e4aa7553e62f11b3f3173766aef9c281783edfd881f7b8299cf35e3ca8caebe73d8464528c907a164df"; };
"@types/cli-progress@npm:3.11.0" = { filename = "@types-cli-progress-npm-3.11.0-889a906352-d440162233.zip"; sha512 = "d4401622333e888925b47c5d5bb0b89dddae17cc020f909a64ad7275b326bf3c6e9cd467f625a197fd958a1e49220d32f4a2b0bf2948fee330c719a9b985674e"; };
"@types/convert-excel-to-json@npm:1.7.1" = { filename = "@types-convert-excel-to-json-npm-1.7.1-7a1bdb855f-69daf5ff8e.zip"; sha512 = "69daf5ff8eb9f6350e22d3140b3dc942051435ddfac09c4b84d41717157aff0d10c766c43115d8672f5f3d1e5092b857504a64f81e859a5053d142c0f600e34d"; };
"cli-progress@npm:3.11.2" = { filename = "cli-progress-npm-3.11.2-6cecb7043d-147d26b80c.zip"; sha512 = "147d26b80ceaa24d72f0354d1b58b7f3567b928bf5943be879de31cf16b0a4f1d059984e2e35a664d7d27ae3e7fafd69fd94b35f462c8879caf96d7f31eac442"; };
"eslint-plugin-prettier@npm:4.2.1" = { filename = "eslint-plugin-prettier-npm-4.2.1-ba8e1240f1-b9e839d233.zip"; sha512 = "b9e839d2334ad8ec7a5589c5cb0f219bded260839a857d7a486997f9870e95106aa59b8756ff3f37202085ebab658de382b0267cae44c3a7f0eb0bcc03a4f6d6"; };
"@playwright/test@npm:1.26.1" = { filename = "@playwright-test-npm-1.26.1-26a6c4c5d3-872bc58dfa.zip"; sha512 = "872bc58dfa8f8a94547b69aaf7e88178213e2201a17aced1b425ef6b13bdd2b53e7274ae8f7ca57dfc189b214be5da5e3290f80b03e5bf5bdc4f3ff0ccd38375"; };
"@typescript-eslint/parser@npm:5.30.4" = { filename = "@typescript-eslint-parser-npm-5.30.4-84cccd38a0-e13ffd0cbb.zip"; sha512 = "e13ffd0cbb691b5b82038a5a1475a7771409398bc90e0430e9b3818174926c5af7c637d5915f7c2949f38201c04bfe57dfc91f4d9052a48ee551faba3b8c7349"; };
"convert-excel-to-json@npm:1.7.0" = { filename = "convert-excel-to-json-npm-1.7.0-0ec067d114-9631b33d6e.zip"; sha512 = "9631b33d6e84cc85def469de099a893ba6fc7304423a0c6c33c9816a6c6c50e8f2ee320974c13baa4b6357ade1b1be8ae953a0f4e626d4ddb4b07cd7594beeca"; };
"@blockfrost/blockfrost-js@npm:5.0.0" = { filename = "@blockfrost-blockfrost-js-npm-5.0.0-199506f8df-8aed650fab.zip"; sha512 = "8aed650fabcbd4923f9abbfe7d67133b6cfd637f0f6c667d13fdf2bd4ee4597b1383a9f6fefb1128b50831433d2afaa5069c7d087da9b02fc1bff06d8925cc5d"; };
"@types/node@npm:18.7.23" = { filename = "@types-node-npm-18.7.23-070e968159-2c8df0830d.zip"; sha512 = "2c8df0830d8345e5cd1ca17feb9cf43fa667aae749888e0a068c5c1b35eaedd2f9b24ed987a0758078395edf7a03681e5e0b7790a518ff7afe1ff6d8459f7b4a"; };
"playwright-core@npm:1.26.1" = { filename = "playwright-core-npm-1.26.1-f9bbf8ed6c-6347224c28.zip"; sha512 = "6347224c28c1ec21d49b659ae35452955e2d8a8ff7aa578f0a0dbb1eccfbcea97e7400446335e966c2a1cbb356381d78131ea65e4a2f19a3eccfb58d33aed0ca"; };
"prettier-linter-helpers@npm:1.0.0" = { filename = "prettier-linter-helpers-npm-1.0.0-6925131a7e-00ce8011cf.zip"; sha512 = "00ce8011cf6430158d27f9c92cfea0a7699405633f7f1d4a45f07e21bf78e99895911cbcdc3853db3a824201a7c745bd49bfea8abd5fb9883e765a90f74f8392"; };
"js-xlsx@npm:0.8.22" = { filename = "js-xlsx-npm-0.8.22-99d6077d07-41474bfc7c.zip"; sha512 = "41474bfc7cfaa2ce6acc8736acbd512c894f24b2ffd11990900f9a7ddd2008fd0882ceef60a96d5f1de4631088d0624bb2b632522c21198d972d1161b03e8b16"; };
"xlsx@npm:0.18.5" = { filename = "xlsx-npm-0.18.5-f70d417ac6-c5774d3c6a.zip"; sha512 = "c5774d3c6abdf2db24f33a7b786e305255dac0e41a4e6bf6167c3f8517bfb5bfcb98e8207c39d5105f8304aa7416758da0400a993fb79aaf8e2ea4cfa8801f2e"; };
"@typescript-eslint/eslint-plugin@npm:5.38.1" = { filename = "@typescript-eslint-eslint-plugin-npm-5.38.1-a0d314dce5-a889558802.zip"; sha512 = "a8895588022f75b2bf994ce52f7109d8814e0f5b3bef0d4fac19dc86a926202ca204bfca8c0e5a033d7566bae90815a772b64bcdc61c349f47ddd52d91989de5"; };
"@typescript-eslint/types@npm:5.30.4" = { filename = "@typescript-eslint-types-npm-5.30.4-c748bd84f1-06181c3355.zip"; sha512 = "06181c33551850492ccfd48232f93083c6cf9205d26b26fe6e356b7a4ebb08beffd89ae3b84011da94ffd0e6948422d91d94df7005edeca1c8348117d4776715"; };
"string-width@npm:4.2.3" = { filename = "string-width-npm-4.2.3-2c27177bae-e52c10dc3f.zip"; sha512 = "e52c10dc3fbfcd6c3a15f159f54a90024241d0f149cf8aed2982a2d801d2e64df0bf1dc351cf8e95c3319323f9f220c16e740b06faecd53e2462df1d2b5443fb"; };
"@emurgo/cardano-serialization-lib-nodejs@npm:10.2.0" = { filename = "@emurgo-cardano-serialization-lib-nodejs-npm-10.2.0-220a08c8b9-4337c4b57d.zip"; sha512 = "4337c4b57d6c980ffa0263e9c4d1819deb25d4b70042524f4f61b24826e6aef5e316e0a29026bc53f423a2337013b33e201b18cd4abe5bc5591f3214dbeda244"; };
"bottleneck@npm:2.19.5" = { filename = "bottleneck-npm-2.19.5-2c6092aa17-c5eef1bbea.zip"; sha512 = "c5eef1bbea12cef1f1405e7306e7d24860568b0f7ac5eeab706a86762b3fc65ef6d1c641c8a166e4db90f412fc5c948fc5ce8008a8cd3d28c7212ef9c3482bda"; };
"debug@npm:4.3.4" = { filename = "debug-npm-4.3.4-4513954577-3dbad3f94e.zip"; sha512 = "3dbad3f94ea64f34431a9cbf0bafb61853eda57bff2880036153438f50fb5a84f27683ba0d8e5426bf41a8c6ff03879488120cf5b3a761e77953169c0600a708"; };
"argparse@npm:1.0.10" = { filename = "argparse-npm-1.0.10-528934e59d-7ca6e45583.zip"; sha512 = "7ca6e45583a28de7258e39e13d81e925cfa25d7d4aacbf806a382d3c02fcb13403a07fb8aeef949f10a7cfe4a62da0e2e807b348a5980554cc28ee573ef95945"; };
"@typescript-eslint/scope-manager@npm:5.30.4" = { filename = "@typescript-eslint-scope-manager-npm-5.30.4-8b6cf23765-3da442dc11.zip"; sha512 = "3da442dc113ee821c6b1c4510ee4cfd6f6f34838587785b7c486d262af913dca66229a47ebb9a63ad605f8edbe57a8387be24c817c8091783b57c33b7862cbcc"; };
"node.extend@npm:2.0.2" = { filename = "node.extend-npm-2.0.2-91a85f1c30-1fe3a1ca7f.zip"; sha512 = "1fe3a1ca7fc35392f169c8a46d889d07deb201bba3a20d17df23efab509698c9639737b0c235c9be772a34035e749bae5d477f74c9e26a1b67c78bd7d6dce8e4"; };
"fast-diff@npm:1.2.0" = { filename = "fast-diff-npm-1.2.0-5ba4171bb6-1b5306eaa9.zip"; sha512 = "1b5306eaa9e826564d9e5ffcd6ebd881eb5f770b3f977fcbf38f05c824e42172b53c79920e8429c54eb742ce15a0caf268b0fdd5b38f6de52234c4a8368131ae"; };
"typescript@patch:typescript@npm%3A4.7.4#~builtin<compat/typescript>::version=4.7.4&hash=701156" = { filename = "typescript-patch-0cb3c99916-9096d8f6c1.zip"; sha512 = "9096d8f6c16cb80ef3bf96fcbbd055bf1c4a43bd14f3b7be45a9fbe7ada46ec977f604d5feed3263b4f2aa7d4c7477ce5f9cd87de0d6feedec69a983f3a4f93e"; };
"@emurgo/cip14-js@npm:3.0.1" = { filename = "@emurgo-cip14-js-npm-3.0.1-6011030ea2-9eaf312410.zip"; sha512 = "9eaf3124108e8c252a745de9ef1f334ab26a32271077b00fe0ea2a06e40838dd435165dac523ebd4d851ae7a94d8c56766dabc372aabffedd36551c798c607c5"; };
"got@npm:11.8.5" = { filename = "got-npm-11.8.5-787b5e3116-2de8a1bbda.zip"; sha512 = "2de8a1bbda4e9b6b2b72b2d2100bc055a59adc1740529e631f61feb44a8b9a1f9f8590941ed9da9df0090b6d6d0ed8ffee94cd9ac086ec3409b392b33440f7d2"; };
"adler-32@npm:1.3.1" = { filename = "adler-32-npm-1.3.1-8493d3a628-c7f6b02df6.zip"; sha512 = "c7f6b02df64a4392fcf1591862344f56733716a558e97a8b06a553dadeeaec792054512389000f42f371b13d2be5370e056e18db3b573944b595c4cb7742c5c6"; };
"commander@npm:9.4.1" = { filename = "commander-npm-9.4.1-9deffb2749-bfb18e325a.zip"; sha512 = "bfb18e325a5bdf772763c2213d5c7d9e77144d944124e988bcd8e5e65fb6d45d5d4e86b09155d0f2556c9a59c31e428720e57968bcd050b2306e910a0bf3cf13"; };
"crc-32@npm:1.2.2" = { filename = "crc-32-npm-1.2.2-28bdc12bcc-ad2d0ad0cb.zip"; sha512 = "ad2d0ad0cbd465b75dcaeeff0600f8195b686816ab5f3ba4c6e052a07f728c3e70df2e3ca9fd3d4484dc4ba70586e161ca5a2334ec8bf5a41bf022a6103ff243"; };
"codepage@npm:1.15.0" = { filename = "codepage-npm-1.15.0-bde3a4eb54-86bdfd8f8f.zip"; sha512 = "86bdfd8f8fd4d78ace6ddab02a1621cbb4a833686fe886984b4155d99cd0287581d69495774b816ab2f571c4dc851c1595e1dbb8d69bd6dbb5a631ebf317fab0"; };
"wmf@npm:1.0.2" = { filename = "wmf-npm-1.0.2-15d4e3e93c-d336acb2c7.zip"; sha512 = "d336acb2c76fa868ef006fbb06c4e64c7c1ed5ff77d16c48a273cf1f4d0a44e35df209b8fde28d93dd4a924d652a9c4fc8a92ad57885a5e437df0b0900769e3b"; };
"word@npm:0.3.0" = { filename = "word-npm-0.3.0-da20365d4a-f84e706188.zip"; sha512 = "f84e7061883380c1bcb0d98bd183b7f2b281688011924af7a96d3ed3ee20aeb12cc59a0451b66e5e57520338a056725ff8e0c07b358c0afecf5488a9557c19fe"; };
"form-data@npm:4.0.0" = { filename = "form-data-npm-4.0.0-916facec2d-01135bf867.zip"; sha512 = "01135bf8675f9d5c61ff18e2e2932f719ca4de964e3be90ef4c36aacfc7b9cb2fceb5eca0b7e0190e3383fe51c5b37f4cb80b62ca06a99aaabfcfd6ac7c9328c"; };
"ignore@npm:5.2.0" = { filename = "ignore-npm-5.2.0-fc4b58a4f3-6b1f926792.zip"; sha512 = "6b1f926792d614f64c6c83da3a1f9c83f6196c2839aa41e1e32dd7b8d174cef2e329d75caabb62cb61ce9dc432f75e67d07d122a037312db7caa73166a1bdb77"; };
"regexpp@npm:3.2.0" = { filename = "regexpp-npm-3.2.0-2513f32cfc-a78dc5c715.zip"; sha512 = "a78dc5c7158ad9ddcfe01aa9144f46e192ddbfa7b263895a70a5c6c73edd9ce85faf7c0430e59ac38839e1734e275b9c3de5c57ee3ab6edc0e0b1bdebefccef8"; };
"emoji-regex@npm:8.0.0" = { filename = "emoji-regex-npm-8.0.0-213764015c-d4c5c39d5a.zip"; sha512 = "d4c5c39d5a9868b5fa152f00cada8a936868fd3367f33f71be515ecee4c803132d11b31a6222b2571b1e5f7e13890156a94880345594d0ce7e3c9895f560f192"; };
"is-fullwidth-code-point@npm:3.0.0" = { filename = "is-fullwidth-code-point-npm-3.0.0-1ecf4ebee5-44a30c2945.zip"; sha512 = "44a30c29457c7fb8f00297bce733f0a64cd22eca270f83e58c105e0d015e45c019491a4ab2faef91ab51d4738c670daff901c799f6a700e27f7314029e99e348"; };
"magicli@npm:0.0.8" = { filename = "magicli-npm-0.0.8-31f7850a79-8035cf39b3.zip"; sha512 = "8035cf39b329d072c583a7ea07ef043127d8a10567c34bfd031d136b45d040c5fd9aa65445ddb87a303f43e827d866da50e8548cede980f1c15d4f5e4a197634"; };
"jszip@npm:2.4.0" = { filename = "jszip-npm-2.4.0-29a815b5fb-ac14ad5cfb.zip"; sha512 = "ac14ad5cfb5b58963b8cf084eb3f303044cd5bdbe965a47fa0431ade7ee550b878d8f6f395320cda8142b4dab379956a05897ebbc0839d83e10910d2c5332fd3"; };
"ssf@npm:0.11.2" = { filename = "ssf-npm-0.11.2-e6437eb624-6ecef6ae0a.zip"; sha512 = "6ecef6ae0a90e67dc4b05bc3cca883e2dffad9773b41124af36ee308884e4a29f98bde66d6c8d2bd1ccf5f860ea4f6c49338bd8d733007fc42ebe02dd5295dcf"; };
"semver@npm:7.3.7" = { filename = "semver-npm-7.3.7-3bfe704194-2fa3e87756.zip"; sha512 = "2fa3e877568cd6ce769c75c211beaed1f9fce80b28338cadd9d0b6c40f2e2862bafd62c19a6cff42f3d54292b7c623277bcab8816a2b5521cf15210d43e75232"; };
"tsutils@npm:3.21.0" = { filename = "tsutils-npm-3.21.0-347e6636c5-1843f4c1b2.zip"; sha512 = "1843f4c1b2e0f975e08c4c21caa4af4f7f65a12ac1b81b3b8489366826259323feb3fc7a243123453d2d1a02314205a7634e048d4a8009921da19f99755cdc48"; };
"ms@npm:2.1.2" = { filename = "ms-npm-2.1.2-ec0c1512ff-673cdb2c31.zip"; sha512 = "673cdb2c3133eb050c745908d8ce632ed2c02d85640e2edb3ace856a2266a813b30c613569bf3354fdf4ea7d1a1494add3bfa95e2713baa27d0c2c71fc44f58f"; };
"strip-ansi@npm:6.0.1" = { filename = "strip-ansi-npm-6.0.1-caddc7cb40-f3cd25890a.zip"; sha512 = "f3cd25890aef3ba6e1a74e20896c21a46f482e93df4a06567cebf2b57edabb15133f1f94e57434e0a958d61186087b1008e89c94875d019910a213181a14fc8c"; };
"sprintf-js@npm:1.0.3" = { filename = "sprintf-js-npm-1.0.3-73f0a322fa-19d79aec21.zip"; sha512 = "19d79aec211f09b99ec3099b5b2ae2f6e9cdefe50bc91ac4c69144b6d3928a640bb6ae5b3def70c2e85a2c3d9f5ec2719921e3a59d3ca3ef4b2fd1a4656a0df3"; };
"eslint-plugin-import@npm:2.26.0" = { filename = "eslint-plugin-import-npm-2.26.0-959fe14a01-0bf77ad803.zip"; sha512 = "0bf77ad80339554481eafa2b1967449e1f816b94c7a6f9614ce33fb4083c4e6c050f10d241dd50b4975d47922880a34de1e42ea9d8e6fd663ebb768baa67e655"; };
"cfb@npm:1.2.2" = { filename = "cfb-npm-1.2.2-df6fc7d448-cfb63a7d63.zip"; sha512 = "cfb63a7d630a7fa415c1b25655dca66666584f29c95fb0ee90866ada1a28090857827f2ba70a9a50df28bdce05728ae58d495bce417249f305ef7b3c85840024"; };
"ts-node@npm:10.9.1" = { filename = "ts-node-npm-10.9.1-6c268be7f4-090adff130.zip"; sha512 = "090adff1302ab20bd3486e6b4799e90f97726ed39e02b39e566f8ab674fd5bd5f727f43615debbfc580d33c6d9d1c6b1b3ce7d8e3cca3e20530a145ffa232c35"; };
"@typescript-eslint/scope-manager@npm:5.38.1" = { filename = "@typescript-eslint-scope-manager-npm-5.38.1-24ac315081-c3b38ca007.zip"; sha512 = "c3b38ca0074d09e26c30b4385c18933f8a6418c923a24c7f4c2297af60a85d604320f119863676f49ea4254b3c01c112504547436eda4951ade609e8d7f438a7"; };
"is@npm:3.3.0" = { filename = "is-npm-3.3.0-90b1d93580-81fad3b40c.zip"; sha512 = "81fad3b40c606984c2d0699207c4c48d2a0d29cc834b274d0b74c172f3eeebdb981301fe0d690ce090a96bf021a8a1f8b1325262ad9870c525e557ac4a559c56"; };
"eslint-plugin-unicorn@npm:43.0.2" = { filename = "eslint-plugin-unicorn-npm-43.0.2-bd71d6ceec-1b63eb013c.zip"; sha512 = "1b63eb013cbc0b3c9ef131a1e049b4b53d8e208393675d5f97d3fa83c050ebcb695a7fd210f4de1460f42f89c2ecca261280488834591d5c21e146d297a9ee2e"; };
"codepage@npm:1.3.8" = { filename = "codepage-npm-1.3.8-a74ee7ba6b-6f1fb3eb47.zip"; sha512 = "6f1fb3eb47452853e66107948dbc8a084739cbd6a299e2dfe065937ac363aee4aeca4064de7c3d833830b0a3e6d51a882d7bdf45633793e5cb64aecd50e6c45b"; };
"ssf@npm:0.8.2" = { filename = "ssf-npm-0.8.2-cf71d8ff3d-24b0074710.zip"; sha512 = "24b0074710e254d17d463ea1aca70e031f1a4a1aef1f1733c95313551106be5f550e34c0cdd4607ad76a44b876c33d17a3d59d4ae4d1bdb770fb31c1ae42e9b6"; };
"bech32@npm:2.0.0" = { filename = "bech32-npm-2.0.0-ad98b7dd79-fa15acb270.zip"; sha512 = "fa15acb270b59aa496734a01f9155677b478987b773bf701f465858bf1606c6a970085babd43d71ce61895f1baa594cb41a2cd1394bd2c6698f03cc2d811300e"; };
"@typescript-eslint/typescript-estree@npm:5.30.4" = { filename = "@typescript-eslint-typescript-estree-npm-5.30.4-7c97ea55f3-1aaa414993.zip"; sha512 = "1aaa414993a4e35927e93f929d34a6e07cb8ec46c4ea9a58f018c36ff1fc3027ca5007e6abe922c5869557cd2d7f319e8c57cccd618517781979e669d3b704d0"; };
"has@npm:1.0.3" = { filename = "has-npm-1.0.3-b7f00631c1-b9ad53d53b.zip"; sha512 = "b9ad53d53be4af90ce5d1c38331e712522417d017d5ef1ebd0507e07c2fbad8686fffb8e12ddecd4c39ca9b9b47431afbb975b8abf7f3c3b82c98e9aad052792"; };
"xlsx@npm:0.12.13" = { filename = "xlsx-npm-0.12.13-c322f02f6c-f52a546084.zip"; sha512 = "f52a5460842274b7562f5b3f4b7bfee5c40c0701c199e2fa321d062563f6c084288820eed2bb7941ba8c1ea3fea88da333b7fc9f1f463d1f7d49454d4b1e5288"; };
"@sindresorhus/is@npm:4.6.0" = { filename = "@sindresorhus-is-npm-4.6.0-7cad05c55e-83839f13da.zip"; sha512 = "83839f13da2c29d55c97abc3bc2c55b250d33a0447554997a85c539e058e57b8da092da396e252b11ec24a0279a0bed1f537fa26302209327060643e327f81d2"; };
"cacheable-lookup@npm:5.0.4" = { filename = "cacheable-lookup-npm-5.0.4-8f13e8b44b-763e02cf91.zip"; sha512 = "763e02cf9196bc9afccacd8c418d942fc2677f22261969a4c2c2e760fa44a2351a81557bd908291c3921fe9beb10b976ba8fa50c5ca837c5a0dd945f16468f2d"; };
"lowercase-keys@npm:2.0.0" = { filename = "lowercase-keys-npm-2.0.0-1876065a32-24d7ebd56c.zip"; sha512 = "24d7ebd56ccdf15ff529ca9e08863f3c54b0b9d1edb97a3ae1af34940ae666c01a1e6d200707bce730a8ef76cb57cc10e65f245ecaaf7e6bc8639f2fb460ac23"; };
"p-cancelable@npm:2.1.1" = { filename = "p-cancelable-npm-2.1.1-9388305f02-3dba12b4fb.zip"; sha512 = "3dba12b4fb4a1e3e34524535c7858fc82381bbbd0f247cc32dedc4018592a3950ce66b106d0880b4ec4c2d8d6576f98ca885dc1d7d0f274d1370be20e9523ddf"; };
"asynckit@npm:0.4.0" = { filename = "asynckit-npm-0.4.0-c718858525-7b78c451df.zip"; sha512 = "7b78c451df768adba04e2d02e63e2d0bf3b07adcd6e42b4cf665cb7ce899bedd344c69a1dcbce355b5f972d597b25aaa1c1742b52cffd9caccb22f348114f6be"; };
"@typescript-eslint/type-utils@npm:5.38.1" = { filename = "@typescript-eslint-type-utils-npm-5.38.1-c212f64f32-1e5fbb5cd2.zip"; sha512 = "1e5fbb5cd2cd97d8d6aaf6b0d1262517e74aba006ffc61526528352a8ab99205456d6247da8252388e868ed7ee8f6c2fa8e108dad68b696cbdbcef6473579173"; };
"@typescript-eslint/visitor-keys@npm:5.30.4" = { filename = "@typescript-eslint-visitor-keys-npm-5.30.4-19f4a2caf4-ec39680a89.zip"; sha512 = "ec39680a89b058e8350adc084c2a957e83161e87ac9732c9fef8fd3045ce5004e059b2ddb0c366192806e3998bf3263c8bbb2cc74a4f2ad3313154ed35dd479a"; };
"@szmarczak/http-timer@npm:4.0.6" = { filename = "@szmarczak-http-timer-npm-4.0.6-6ace00d82d-c29df3bcec.zip"; sha512 = "c29df3bcec6fc3bdec2b17981d89d9c9fc9bd7d0c9bcfe92821dc533f4440bc890ccde79971838b4ceed1921d456973c4180d7175ee1d0023ad0562240a58d95"; };
"@types/responselike@npm:1.0.0" = { filename = "@types-responselike-npm-1.0.0-85dd08af42-e99fc7cc62.zip"; sha512 = "e99fc7cc6265407987b30deda54c1c24bb1478803faf6037557a774b2f034c5b097ffd65847daa87e82a61a250d919f35c3588654b0fdaa816906650f596d1b0"; };
"decompress-response@npm:6.0.0" = { filename = "decompress-response-npm-6.0.0-359de2878c-d377cf47e0.zip"; sha512 = "d377cf47e02d805e283866c3f50d3d21578b779731e8c5072d6ce8c13cc31493db1c2f6784da9d1d5250822120cefa44f1deab112d5981015f2e17444b763812"; };
"responselike@npm:2.0.1" = { filename = "responselike-npm-2.0.1-7f64b6e122-b122535466.zip"; sha512 = "b122535466e9c97b55e69c7f18e2be0ce3823c5d47ee8de0d9c0b114aa55741c6db8bfbfce3766a94d1272e61bfb1ebf0a15e9310ac5629fbb7446a861b4fd3a"; };
"pako@npm:0.2.9" = { filename = "pako-npm-0.2.9-c88ac0d326-055f9487cd.zip"; sha512 = "055f9487cd57fbb78df84315873bbdd089ba286f3499daed47d2effdc6253e981f5db6898c23486de76d4a781559f890d643bd3a49f70f1b4a18019c98aa5125"; };
"frac@npm:1.1.2" = { filename = "frac-npm-1.1.2-7e88efac4e-fbfbb28003.zip"; sha512 = "fbfbb28003bb84506dd35e7aad8543c5a358bdc95451d0065b6127d40d2c45106f14221575c3e9ce3ea4bf0bbf1225b73c5d655965c9f4ce44332cbe1b34667d"; };
"blake2b@npm:2.1.3" = { filename = "blake2b-npm-2.1.3-b5b61ec9ad-e652234249.zip"; sha512 = "e652234249cbdb3345488d52b5e76e8572b8e5333f3f0d5e716772b7c5d2142f433c3fe86130e92117329532e1d1235cdaa89f40bbca27a8ae528bef428241ef"; };
"combined-stream@npm:1.0.8" = { filename = "combined-stream-npm-1.0.8-dc14d4a63a-49fa4aeb49.zip"; sha512 = "49fa4aeb4916567e33ea81d088f6584749fc90c7abec76fd516bf1c5aa5c79f3584b5ba3de6b86d26ddd64bae5329c4c7479343250cfe71c75bb366eae53bb7c"; };
"mime-types@npm:2.1.35" = { filename = "mime-types-npm-2.1.35-dd9ea9f3e2-89a5b7f1de.zip"; sha512 = "89a5b7f1def9f3af5dad6496c5ed50191ae4331cc5389d7c521c8ad28d5fdad2d06fd81baf38fed813dc4e46bb55c8145bb0ff406330818c9cf712fb2e9b3836"; };
"tslib@npm:1.14.1" = { filename = "tslib-npm-1.14.1-102499115e-dbe628ef87.zip"; sha512 = "dbe628ef87f66691d5d2959b3e41b9ca0045c3ee3c7c7b906cc1e328b39f199bb1ad9e671c39025bd56122ac57dfbf7385a94843b1cc07c60a4db74795829acd"; };
"ansi-regex@npm:5.0.1" = { filename = "ansi-regex-npm-5.0.1-c963a48615-2aa4bb54ca.zip"; sha512 = "2aa4bb54caf2d622f1afdad09441695af2a83aa3fe8b8afa581d205e57ed4261c183c4d3877cee25794443fde5876417d859c108078ab788d6af7e4fe52eb66b"; };
"find-up@npm:2.1.0" = { filename = "find-up-npm-2.1.0-9f6cb1765c-43284fe4da.zip"; sha512 = "43284fe4da09f89011f08e3c32cd38401e786b19226ea440b75386c1b12a4cb738c94969808d53a84f564ede22f732c8409e3cfc3f7fb5b5c32378ad0bbf28bd"; };
"for-each-property@npm:0.0.4" = { filename = "for-each-property-npm-0.0.4-9925aacbe8-89f11aa88f.zip"; sha512 = "89f11aa88f083369ba2c00e2da66428184327780781971a9e252c7d1754f6e353686e651fa4876388a0581f3ff8c6f6e7e943a42b3208333d9b87671a20e0b11"; };
"http2-wrapper@npm:1.0.3" = { filename = "http2-wrapper-npm-1.0.3-5b58ade1df-74160b862e.zip"; sha512 = "74160b862ec699e3f859739101ff592d52ce1cb207b7950295bf7962e4aa1597ef709b4292c673bece9c9b300efad0559fc86c71b1409c7a1e02b7229456003e"; };
"@tsconfig/node10@npm:1.0.9" = { filename = "@tsconfig-node10-npm-1.0.9-f2e2d20feb-a33ae4dc2a.zip"; sha512 = "a33ae4dc2a621c0678ac8ac4bceb8e512ae75dac65417a2ad9b022d9b5411e863c4c198b6ba9ef659e14b9fb609bbec680841a2e84c1172df7a5ffcf076539df"; };
"@tsconfig/node12@npm:1.0.11" = { filename = "@tsconfig-node12-npm-1.0.11-9710d1c61b-5ce29a41b1.zip"; sha512 = "5ce29a41b13e7897a58b8e2df11269c5395999e588b9a467386f99d1d26f6c77d1af2719e407621412520ea30517d718d5192a32403b8dfcc163bf33e40a338a"; };
"@tsconfig/node14@npm:1.0.3" = { filename = "@tsconfig-node14-npm-1.0.3-15321421d2-19275fe80c.zip"; sha512 = "19275fe80c4c8d0ad0abed6a96dbf00642e88b220b090418609c4376e1cef81bf16237bf170ad1b341452feddb8115d8dd2e5acdfdea1b27422071163dc9ba9d"; };
"@tsconfig/node16@npm:1.0.3" = { filename = "@tsconfig-node16-npm-1.0.3-6a4a30eda2-3a8b657dd0.zip"; sha512 = "3a8b657dd047495b7ad23437d6afd20297ce90380ff0bdee93fc7d39a900dbd8d9e26e53ff6b465e7967ce2adf0b218782590ce9013285121e6a5928fbd6819f"; };
"acorn-walk@npm:8.2.0" = { filename = "acorn-walk-npm-8.2.0-2f2cac3177-1715e76c01.zip"; sha512 = "1715e76c01dd7b2d4ca472f9c58968516a4899378a63ad5b6c2d668bba8da21a71976c14ec5f5b75f887b6317c4ae0b897ab141c831d741dc76024d8745f1ad1"; };
"acorn@npm:8.8.0" = { filename = "acorn-npm-8.8.0-9ef399ab45-7270ca82b2.zip"; sha512 = "7270ca82b242eafe5687a11fea6e088c960af712683756abf0791b68855ea9cace3057bd5e998ffcef50c944810c1e0ca1da526d02b32110e13c722aa959afdc"; };
"arg@npm:4.1.3" = { filename = "arg-npm-4.1.3-1748b966a8-544af8dd3f.zip"; sha512 = "544af8dd3f60546d3e4aff084d451b96961d2267d668670199692f8d054f0415d86fc5497d0e641e91546f0aa920e7c29e5250e99fc89f5552a34b5d93b77f43"; };
"create-require@npm:1.1.1" = { filename = "create-require-npm-1.1.1-839884ca2e-a9a1503d43.zip"; sha512 = "a9a1503d4390d8b59ad86f4607de7870b39cad43d929813599a23714831e81c520bddf61bcdd1f8e30f05fd3a2b71ae8538e946eb2786dc65c2bbc520f692eff"; };
"diff@npm:4.0.2" = { filename = "diff-npm-4.0.2-73133c7102-f2c09b0ce4.zip"; sha512 = "f2c09b0ce4e6b301c221addd83bf3f454c0bc00caa3dd837cf6c127d6edf7223aa2bbe3b688feea110b7f262adbfc845b757c44c8a9f8c0c5b15d8fa9ce9d20d"; };
"make-error@npm:1.3.6" = { filename = "make-error-npm-1.3.6-ccb85d9458-b86e5e0e25.zip"; sha512 = "b86e5e0e25f7f777b77fabd8e2cbf15737972869d852a22b7e73c17623928fccb826d8e46b9951501d3f20e51ad74ba8c59ed584f610526a48f8ccf88aaec402"; };
"v8-compile-cache-lib@npm:3.0.1" = { filename = "v8-compile-cache-lib-npm-3.0.1-4886071ece-78089ad549.zip"; sha512 = "78089ad549e21bcdbfca10c08850022b22024cdcc2da9b168bcf5a73a6ed7bf01a9cebb9eac28e03cd23a684d81e0502797e88f3ccd27a32aeab1cfc44c39da0"; };
"yn@npm:3.1.1" = { filename = "yn-npm-3.1.1-8ad4259784-2c487b0e14.zip"; sha512 = "2c487b0e149e746ef48cda9f8bad10fc83693cd69d7f9dcd8be4214e985de33a29c9e24f3c0d6bcf2288427040a8947406ab27f7af67ee9456e6b84854f02dd6"; };
"@typescript-eslint/types@npm:5.38.1" = { filename = "@typescript-eslint-types-npm-5.38.1-25ef03dead-384f7fe9a1.zip"; sha512 = "384f7fe9a1995d87507049a868aa1a1f9eb28af913e704540e1494c8c630985f9ef4f4e6bdd4df0d83cbe4611c4e6f4f07d5d91bfa57c88242fb227a6d828b7e"; };
"@typescript-eslint/utils@npm:5.38.1" = { filename = "@typescript-eslint-utils-npm-5.38.1-f0191b30c9-06646ddeb6.zip"; sha512 = "06646ddeb6c1a5dac01e8336dff458cf37dff0d3d5a2f304048a4d6d8f62d504c5330a8b046ec66f6777f324bc1afe6a3f7ea1c5b015b123ab7062e8e22aff67"; };
"lru-cache@npm:6.0.0" = { filename = "lru-cache-npm-6.0.0-b4c8668fe1-f97f499f89.zip"; sha512 = "f97f499f898f23e4585742138a22f22526254fdba6d75d41a1c2526b3b6cc5747ef59c5612ba7375f42aca4f8461950e925ba08c991ead0651b4918b7c978297"; };
"debug@npm:2.6.9" = { filename = "debug-npm-2.6.9-7d4cb597dc-d2f51589ca.zip"; sha512 = "d2f51589ca66df60bf36e1fa6e4386b318c3f1e06772280eea5b1ae9fd3d05e9c2b7fd8a7d862457d00853c75b00451aa2d7459b924629ee385287a650f58fe6"; };
"doctrine@npm:2.1.0" = { filename = "doctrine-npm-2.1.0-ac15d049b7-a45e277f7f.zip"; sha512 = "a45e277f7feaed309fe658ace1ff286c6e2002ac515af0aaf37145b8baa96e49899638c7cd47dccf84c3d32abfc113246625b3ac8f552d1046072adee13b0dc8"; };
"eslint-module-utils@npm:2.7.4" = { filename = "eslint-module-utils-npm-2.7.4-a1640084cb-5da13645da.zip"; sha512 = "5da13645daff145a5c922896b258f8bba560722c3767254e458d894ff5fbb505d6dfd945bffa932a5b0ae06714da2379bd41011c4c20d2d59cc83e23895360f7"; };
"is-core-module@npm:2.10.0" = { filename = "is-core-module-npm-2.10.0-6dff9310aa-0f3f77811f.zip"; sha512 = "0f3f77811f430af3256fa7bbc806f9639534b140f8ee69476f632c3e1eb4e28a38be0b9d1b8ecf596179c841b53576129279df95e7051d694dac4ceb6f967593"; };
"is-glob@npm:4.0.3" = { filename = "is-glob-npm-4.0.3-cb87bf1bdb-d381c1319f.zip"; sha512 = "d381c1319fcb69d341cc6e6c7cd588e17cd94722d9a32dbd60660b993c4fb7d0f19438674e68dfec686d09b7c73139c9166b47597f846af387450224a8101ab4"; };
"minimatch@npm:3.1.2" = { filename = "minimatch-npm-3.1.2-9405269906-c154e56640.zip"; sha512 = "c154e566406683e7bcb746e000b84d74465b3a832c45d59912b9b55cd50dee66e5c4b1e5566dba26154040e51672f9aa450a9aef0c97cfc7336b78b7afb9540a"; };
"@babel/helper-validator-identifier@npm:7.19.1" = { filename = "@babel-helper-validator-identifier-npm-7.19.1-d84f19e1dc-0eca5e86a7.zip"; sha512 = "0eca5e86a729162af569b46c6c41a63e18b43dbe09fda1d2a3c8924f7d617116af39cac5e4cd5d431bb760b4dca3c0970e0c444789b1db42bcf1fa41fbad0a3a"; };
"ci-info@npm:3.4.0" = { filename = "ci-info-npm-3.4.0-f81991d948-7f66073017.zip"; sha512 = "7f660730170a6ce248e173b670587a0c583e31526d21afcd21f77c811c1aaeb8926999081542d1f30e12cce1df582d4c88709fa45f44c00498b46bdf21d4d21a"; };
"indent-string@npm:4.0.0" = { filename = "indent-string-npm-4.0.0-7b717435b2-824cfb9929.zip"; sha512 = "824cfb9929d031dabf059bebfe08cf3137365e112019086ed3dcff6a0a7b698cb80cf67ccccde0e25b9e2d7527aa6cc1fed1ac490c752162496caba3e6699612"; };
"lodash@npm:4.17.21" = { filename = "lodash-npm-4.17.21-6382451519-eb835a2e51.zip"; sha512 = "eb835a2e51d381e561e508ce932ea50a8e5a68f4ebdd771ea240d3048244a8d13658acbd502cd4829768c56f2e16bdd4340b9ea141297d472517b83868e677f7"; };
"pluralize@npm:8.0.0" = { filename = "pluralize-npm-8.0.0-f5f044ed52-08931d4a6a.zip"; sha512 = "08931d4a6a4a5561a7f94f67a31c17e6632cb21e459ab3ff4f6f629d9a822984cf8afef2311d2005fbea5d7ef26016ebb090db008e2d8bce39d0a9a9d218736e"; };
"regexp-tree@npm:0.1.24" = { filename = "regexp-tree-npm-0.1.24-b265ab7f23-5807013289.zip"; sha512 = "5807013289d9205288d665e0f8d8cff94843dfd55fdedd1833eb9d9bbd07188a37dfa02942ec5cdc671180037f715148fac1ba6f18fd6be4268e5a8feb49d340"; };
"voc@npm:1.2.0" = { filename = "voc-npm-1.2.0-49b7da4f71-35a4d35a66.zip"; sha512 = "35a4d35a664149f38a5366b8dd7191dabf0779faac3d3f8b7904e644e484154b45c849763e163391d0aa7328143304157250bb2d5ccddb3baeee5922bd98c1aa"; };
"colors@npm:0.6.2" = { filename = "colors-npm-0.6.2-cb32762d12-3f48cadb26.zip"; sha512 = "3f48cadb26ef1809847f3c0ff1e1dc4b2e2af4ace54dd9cd7491bfcaafef3abaac7cb063cb91f98f305bba8a6fa74720a8856610629f9c889b1eb4cd84a120a3"; };
"frac@npm:0.3.1" = { filename = "frac-npm-0.3.1-f01aab7769-961c6d822c.zip"; sha512 = "961c6d822c6f58a4b03f51ec28bf798a3cb61f90335a5dccfd8c23335179275573218c4cca3dd068d02445271cce20d420335bad279b45d6095e14e93af2a135"; };
"@cspotcode/source-map-support@npm:0.8.1" = { filename = "@cspotcode-source-map-support-npm-0.8.1-964f2de99d-5718f26708.zip"; sha512 = "5718f267085ed8edb3e7ef210137241775e607ee18b77d95aa5bd7514f47f5019aa2d82d96b3bf342ef7aa890a346fa1044532ff7cc3009e7d24fce3ce6200fa"; };
"inspect-property@npm:0.0.6" = { filename = "inspect-property-npm-0.0.6-71f3aac1b9-1f7004478c.zip"; sha512 = "1f7004478ceda8d199e069816ab90b2bea99d6f1aa26b71f582f0e5e413298831a5478d19c0209833c5d70129804cc3d1605f8099509a354a16b8554fb5f831a"; };
"function-bind@npm:1.1.1" = { filename = "function-bind-npm-1.1.1-b56b322ae9-b32fbaebb3.zip"; sha512 = "b32fbaebb3f8ec4969f033073b43f5c8befbb58f1a79e12f1d7490358150359ebd92f49e72ff0144f65f2c48ea2a605bff2d07965f548f6474fd8efd95bf361a"; };
"commander@npm:2.15.1" = { filename = "commander-npm-2.15.1-f80ddc8503-a1b6b66a98.zip"; sha512 = "a1b6b66a98cd1862084fcb230d11f56d3af0e5a42c307158d987464d65112fd9f8de2a682895247d2e475f925895e70e5bda21379b1286b21c55dd5c17f0d5fa"; };
"exit-on-epipe@npm:1.0.1" = { filename = "exit-on-epipe-npm-1.0.1-1aade96e24-e8ab494041.zip"; sha512 = "e8ab4940416d19f311b3c9226e3725c6c4c6026fe682266ecc0ff33a455d585fe3e4ee757857c7bf1d0491b478cb232b8e395dfb438e65ac87317eda47304c32"; };
"eslint-import-resolver-node@npm:0.3.6" = { filename = "eslint-import-resolver-node-npm-0.3.6-d9426786c6-6266733af1.zip"; sha512 = "6266733af1e112970e855a5bcc2d2058fb5ae16ad2a6d400705a86b29552b36131ffc5581b744c23d550de844206fb55e9193691619ee4dbf225c4bde526b1c8"; };
"clean-regexp@npm:1.0.0" = { filename = "clean-regexp-npm-1.0.0-f349f98f15-0b1ce281b0.zip"; sha512 = "0b1ce281b07da2463c6882ea2e8409119b6cabbd9f687cdbdcee942c45b2b9049a2084f7b5f228c63ef9f21e722963ae0bfe56a735dbdbdd92512867625a7e40"; };
"eslint-utils@npm:3.0.0" = { filename = "eslint-utils-npm-3.0.0-630b3a4013-0668fe02f5.zip"; sha512 = "0668fe02f5adab2e5a367eee5089f4c39033af20499df88fe4e6aba2015c20720404d8c3d6349b6f716b08fdf91b9da4e5d5481f265049278099c4c836ccb619"; };
"esquery@npm:1.4.0" = { filename = "esquery-npm-1.4.0-f39408b1a7-a0807e17ab.zip"; sha512 = "a0807e17abd7fbe5fbd4fab673038d6d8a50675cdae6b04fbaa520c34581be0c5fa24582990e8acd8854f671dd291c78bb2efb9e0ed5b62f33bac4f9cf820210"; };
"is-builtin-module@npm:3.2.0" = { filename = "is-builtin-module-npm-3.2.0-8f435dc375-0315751b89.zip"; sha512 = "0315751b898feff0646511c896e88b608a755c5025d0ce9a3ad25783de50be870e47dafb838cebbb06fbb2a948b209ea55348eee267836c9dd40d3a11ec717d3"; };
"safe-regex@npm:2.1.1" = { filename = "safe-regex-npm-2.1.1-4438cded67-5d734e2193.zip"; sha512 = "5d734e2193c63ef0cb00f60c0244e0f8a30ecb31923633cd34636808d6a7c4c206d650017953ae1db8bc33967c2f06af33488dea6f038f4e38212beb7bed77b4"; };
"strip-indent@npm:3.0.0" = { filename = "strip-indent-npm-3.0.0-519e75a28d-18f045d57d.zip"; sha512 = "18f045d57d9d0d90cd16f72b2313d6364fd2cb4bf85b9f593523ad431c8720011a4d5f08b6591c9d580f446e78855c5334a30fb91aa1560f5d9f95ed1b4a0530"; };
"@types/cacheable-request@npm:6.0.2" = { filename = "@types-cacheable-request-npm-6.0.2-894b6992d5-667d25808d.zip"; sha512 = "667d25808dbf46fe104d6f029e0281ff56058d50c7c1b9182774b3e38bb9c1124f56e4c367ba54f92dbde2d1cc573f26eb0e9748710b2822bc0fd1e5498859c6"; };
"@typescript-eslint/visitor-keys@npm:5.38.1" = { filename = "@typescript-eslint-visitor-keys-npm-5.38.1-94aa1a9778-01c83a4290.zip"; sha512 = "01c83a42900f8ab721bd0857abcc000a15183eb26d2d61cceeaef018a83a91325f48c0112d4356383c41dce23174a305bb3352af4705a61d1da46f8ac0e88340"; };
"eslint-visitor-keys@npm:3.3.0" = { filename = "eslint-visitor-keys-npm-3.3.0-d329af7c8c-d59e68a7c5.zip"; sha512 = "d59e68a7c5a6d0146526b0eec16ce87fbf97fe46b8281e0d41384224375c4e52f5ffb9e16d48f4ea50785cde93f766b0c898e31ab89978d88b0e1720fbfb7808"; };
"ssf@npm:0.10.3" = { filename = "ssf-npm-0.10.3-0738f1093a-03d639bd5e.zip"; sha512 = "03d639bd5ea95e8c148a8c62d5c564036dc58d62fb4337940ec6d935ccaf3506704d5f6caf92f51380eced94aa4e22c193b5a047c2fd55910616b18bdd9e4bf9"; };
"object.values@npm:1.1.5" = { filename = "object.values-npm-1.1.5-f1de7f3742-0f17e99741.zip"; sha512 = "0f17e99741ebfbd0fa55ce942f6184743d3070c61bd39221afc929c8422c4907618c8da694c6915bc04a83ab3224260c779ba37fc07bb668bdc5f33b66a902a4"; };
"defer-to-connect@npm:2.0.1" = { filename = "defer-to-connect-npm-2.0.1-9005cc8c60-8a9b50d2f2.zip"; sha512 = "8a9b50d2f25446c0bfefb55a48e90afd58f85b21bcf78e9207cd7b804354f6409032a1705c2491686e202e64fc05f147aa5aa45f9aa82627563f045937f5791b"; };
"mimic-response@npm:3.1.0" = { filename = "mimic-response-npm-3.1.0-a4a24b4e96-25739fee32.zip"; sha512 = "25739fee32c17f433626bf19f016df9036b75b3d84a3046c7d156e72ec963dd29d7fc8a302f55a3d6c5a4ff24259676b15d915aad6480815a969ff2ec0836867"; };
"resolve@npm:1.22.1" = { filename = "resolve-npm-1.22.1-3980488690-07af5fc1e8.zip"; sha512 = "07af5fc1e81aa1d866cbc9e9460fbb67318a10fa3c4deadc35c3ad8a898ee9a71a86a65e4755ac3195e0ea0cfbe201eb323ebe655ce90526fd61917313a34e4e"; };
"nanoassert@npm:1.1.0" = { filename = "nanoassert-npm-1.1.0-1da45b4766-f360fe639d.zip"; sha512 = "f360fe639db8edc422de9f5a8a7d384ba9c11e9c6fac149f7ad3b0a94e4ec9d5aa44ce55b3e4c7682658efad792604fc96c336b0e80a3590744104ba58af80c7"; };
"delayed-stream@npm:1.0.0" = { filename = "delayed-stream-npm-1.0.0-c5a4c4cc02-46fe6e83e2.zip"; sha512 = "46fe6e83e2cb1d85ba50bd52803c68be9bd953282fa7096f51fc29edd5d67ff84ff753c51966061e5ba7cb5e47ef6d36a91924eddb7f3f3483b1c560f77a0020"; };
"mime-db@npm:1.52.0" = { filename = "mime-db-npm-1.52.0-b5371d6fd2-0d99a03585.zip"; sha512 = "0d99a03585f8b39d68182803b12ac601d9c01abfa28ec56204fa330bc9f3d1c5e14beb049bafadb3dbdf646dfb94b87e24d4ec7b31b7279ef906a8ea9b6a513f"; };
"get-prototype-chain@npm:1.0.1" = { filename = "get-prototype-chain-npm-1.0.1-bf88cf0f44-2d7b8eb2af.zip"; sha512 = "2d7b8eb2af3f620d8dd34e49724cc20ccacf9bcb86969deb436e2caa945339c1993d9ef2f0bfa8e9c7f81a747ecf318b8f502f086e9147707b97dbbb09b5ee28"; };
"adler-32@npm:1.2.0" = { filename = "adler-32-npm-1.2.0-d6cb5d1f89-aa611316fa.zip"; sha512 = "aa611316fa224349b3eb1b7fcccc05195c38e425ff2b678fde67c0440b27074c42ad97b03efb7478f045b094f0dcb51a8711a2d5571d8940e1c5c52593af7bf6"; };
"cfb@npm:1.0.8" = { filename = "cfb-npm-1.0.8-a014cbe2f9-576ae94a4e.zip"; sha512 = "576ae94a4e96a087c01a66eaad301cd5d436924521bca0a32c807725b5ffdf0182cf4346fb9f5c1e9fc8d9327adda1870fc67aba795c4e88f9a0c531e7668998"; };
"codepage@npm:1.13.1" = { filename = "codepage-npm-1.13.1-cd4c6bbd8d-0f769588ad.zip"; sha512 = "0f769588ad7c152e7e90aa6be80d7d5ed851b2f730d34b11d4b70c335a7df393b9eab144ed2d123828fe29794de895c65f1397c07e82630ec56574ad5da5a917"; };
"array.prototype.flat@npm:1.3.0" = { filename = "array.prototype.flat-npm-1.3.0-6c5c4292bd-2a652b3e8d.zip"; sha512 = "2a652b3e8dc0bebb6117e42a5ab5738af0203a14c27341d7bb2431467bdb4b348e2c5dc555dfcda8af0a5e4075c400b85311ded73861c87290a71a17c3e0a257"; };
"tsconfig-paths@npm:3.14.1" = { filename = "tsconfig-paths-npm-3.14.1-17a815b5c5-8afa01c673.zip"; sha512 = "8afa01c673ebb4782ba53d3a12df97fa837ce524f8ad38ee4e2b2fd57f5ac79abc21c574e9e9eb014d93efe7fe8214001b96233b5c6ea75bd1ea82afe17a4c6d"; };
"read-pkg-up@npm:7.0.1" = { filename = "read-pkg-up-npm-7.0.1-11895bed9a-e4e93ce70e.zip"; sha512 = "e4e93ce70e5905b490ca8f883eb9e48b5d3cebc6cd4527c25a0d8f3ae2903bd4121c5ab9c5a3e217ada0141098eeb661313c86fa008524b089b8ed0b7f165e44"; };
"quick-lru@npm:5.1.1" = { filename = "quick-lru-npm-5.1.1-e38e0edce3-a516faa255.zip"; sha512 = "a516faa25574be7947969883e6068dbe4aa19e8ef8e8e0fd96cddd6d36485e9106d85c0041a27153286b0770b381328f4072aa40d3b18a19f5f7d2b78b94b5ed"; };
"resolve-alpn@npm:1.2.1" = { filename = "resolve-alpn-npm-1.2.1-af77edd28b-f558071fcb.zip"; sha512 = "f558071fcb2c60b04054c99aebd572a2af97ef64128d59bef7ab73bd50d896a222a056de40ffc545b633d99b304c259ea9d0c06830d5c867c34f0bfa60b8eae0"; };
"blake2b-wasm@npm:1.1.7" = { filename = "blake2b-wasm-npm-1.1.7-ac747aaa82-be5ebacdd2.zip"; sha512 = "be5ebacdd25076ae5fcaf1c60c37096c85490a36ee1f8e78d5c4c2fb8ccad0fe0e22cecadba6fcf6ed7d91c1aed9c55980811fe064fafb4ccd80ac34a8a326ea"; };
"@types/json-schema@npm:7.0.11" = { filename = "@types-json-schema-npm-7.0.11-79462ae5ca-527bddfe62.zip"; sha512 = "527bddfe62db9012fccd7627794bd4c71beb77601861055d87e3ee464f2217c85fca7a4b56ae677478367bbd248dbde13553312b7d4dbc702a2f2bbf60c4018d"; };
"yallist@npm:4.0.0" = { filename = "yallist-npm-4.0.0-b493d9e907-343617202a.zip"; sha512 = "343617202af32df2a15a3be36a5a8c0c8545208f3d3dfbc6bb7c3e3b7e8c6f8e7485432e4f3b88da3031a6e20afa7c711eded32ddfb122896ac5d914e75848d5"; };
"array-includes@npm:3.1.5" = { filename = "array-includes-npm-3.1.5-6b8e152f4f-f6f24d8341.zip"; sha512 = "f6f24d834179604656b7bec3e047251d5cc87e9e87fab7c175c61af48e80e75acd296017abcde21fb52292ab6a2a449ab2ee37213ee48c8709f004d75983f9c5"; };
"ms@npm:2.0.0" = { filename = "ms-npm-2.0.0-9e1101a471-0e6a22b8b7.zip"; sha512 = "0e6a22b8b746d2e0b65a430519934fefd41b6db0682e3477c10f60c76e947c4c0ad06f63ffdf1d78d335f83edee8c0aa928aa66a36c7cd95b69b26f468d527f4"; };
"esutils@npm:2.0.3" = { filename = "esutils-npm-2.0.3-f865beafd5-22b5b08f74.zip"; sha512 = "22b5b08f74737379a840b8ed2036a5fb35826c709ab000683b092d9054e5c2a82c27818f12604bfc2a9a76b90b6834ef081edbc1c7ae30d1627012e067c6ec87"; };
"is-extglob@npm:2.1.1" = { filename = "is-extglob-npm-2.1.1-0870ea68b5-df033653d0.zip"; sha512 = "df033653d06d0eb567461e58a7a8c9f940bd8c22274b94bf7671ab36df5719791aae15eef6d83bbb5e23283967f2f984b8914559d4449efda578c775c4be6f85"; };
"cacheable-request@npm:7.0.2" = { filename = "cacheable-request-npm-7.0.2-e64cc641fc-6152813982.zip"; sha512 = "6152813982945a5c9989cb457a6c499f12edcc7ade323d2fbfd759abc860bdbd1306e08096916bb413c3c47e812f8e4c0a0cc1e112c8ce94381a960f115bc77f"; };
"concat-stream@npm:2.0.0" = { filename = "concat-stream-npm-2.0.0-8bb2ad5aa0-d7f75d48f0.zip"; sha512 = "d7f75d48f0ecd356c1545d87e22f57b488172811b1181d96021c7c4b14ab8855f5313280263dca44bb06e5222f274d047da3e290a38841ef87b59719bde967c7"; };
"locate-path@npm:2.0.0" = { filename = "locate-path-npm-2.0.0-673d28b0ea-02d581edbb.zip"; sha512 = "02d581edbbbb0fa292e28d96b7de36b5b62c2fa8b5a7e82638ebb33afa74284acf022d3b1e9ae10e3ffb7658fbc49163fcd5e76e7d1baaa7801c3e05a81da755"; };
"debug@npm:3.2.7" = { filename = "debug-npm-3.2.7-754e818c7a-b3d8c59407.zip"; sha512 = "b3d8c5940799914d30314b7c3304a43305fd0715581a919dacb8b3176d024a782062368405b47491516d2091d6462d4d11f2f4974a405048094f8bfebfa3071c"; };
"escape-string-regexp@npm:1.0.5" = { filename = "escape-string-regexp-npm-1.0.5-3284de402f-6092fda75c.zip"; sha512 = "6092fda75c63b110c706b6a9bfde8a612ad595b628f0bd2147eea1d3406723020810e591effc7db1da91d80a71a737a313567c5abb3813e8d9c71f4aa595b410"; };
"eslint-visitor-keys@npm:2.1.0" = { filename = "eslint-visitor-keys-npm-2.1.0-c31806b6b9-e3081d7dd2.zip"; sha512 = "e3081d7dd2611a35f0388bbdc2f5da60b3a3c5b8b6e928daffff7391146b434d691577aa95064c8b7faad0b8a680266bcda0a42439c18c717b80e6718d7e267d"; };
"estraverse@npm:5.3.0" = { filename = "estraverse-npm-5.3.0-03284f8f63-072780882d.zip"; sha512 = "072780882dc8416ad144f8fe199628d2b3e7bbc9989d9ed43795d2c90309a2047e6bc5979d7e2322a341163d22cfad9e21f4110597fe487519697389497e4e2b"; };
"builtin-modules@npm:3.3.0" = { filename = "builtin-modules-npm-3.3.0-db4f3d32de-db021755d7.zip"; sha512 = "db021755d7ed8be048f25668fe2117620861ef6703ea2c65ed2779c9e3636d5c3b82325bd912244293959ff3ae303afa3471f6a15bf5060c103e4cc3a839749d"; };
"min-indent@npm:1.0.1" = { filename = "min-indent-npm-1.0.1-77031f50e1-bfc6dd03c5.zip"; sha512 = "bfc6dd03c5eaf623a4963ebd94d087f6f4bbbfd8c41329a7f09706b0cb66969c4ddd336abeb587bc44bc6f08e13bf90f0b374f9d71f9f01e04adc2cd6f083ef1"; };
"@types/http-cache-semantics@npm:4.0.1" = { filename = "@types-http-cache-semantics-npm-4.0.1-90863c7a3e-1048aacf62.zip"; sha512 = "1048aacf627829f0d5f00184e16548205cd9f964bf0841c29b36bc504509230c40bc57c39778703a1c965a6f5b416ae2cbf4c1d4589c889d2838dd9dbfccf6e9"; };
"eslint-scope@npm:5.1.1" = { filename = "eslint-scope-npm-5.1.1-71fe59b18a-47e4b6a3f0.zip"; sha512 = "47e4b6a3f0cc29c7feedee6c67b225a2da7e155802c6ea13bbef4ac6b9e10c66cd2dcb987867ef176292bf4e64eccc680a49e35e9e9c669f4a02bac17e86abdb"; };
"cliss@npm:0.0.2" = { filename = "cliss-npm-0.0.2-90dac0ae21-f1d3d54adc.zip"; sha512 = "f1d3d54adc07098bff11515ce5ad1208f8b5a38ddf04347e41a7fc6d2f4b4c7a3124dc0d2d34c13a0a05b6ef33a15aa11005753ee216f9b15f590173b3aa064d"; };
"for-each-property-deep@npm:0.0.3" = { filename = "for-each-property-deep-npm-0.0.3-3d029f5400-d13577ca37.zip"; sha512 = "d13577ca373099acaf99bb00a655f5f622838957b7761822b0ade700ec9ef2e49e16e92fed94a9d4990fa591c85c5419d506a209a7ea3ceee1e5decd5861c3b0"; };
"brace-expansion@npm:1.1.11" = { filename = "brace-expansion-npm-1.1.11-fb95eb05ad-faf34a7bb0.zip"; sha512 = "faf34a7bb0c3fcf4b59c7808bc5d2a96a40988addf2e7e09dfbb67a2251800e0d14cd2bfc1aa79174f2f5095c54ff27f46fb1289fe2d77dac755b5eb3434cc07"; };
"@types/keyv@npm:3.1.4" = { filename = "@types-keyv-npm-3.1.4-a8082ea56b-e009a2bfb5.zip"; sha512 = "e009a2bfb50e90ca9b7c6e8f648f8464067271fd99116f881073fa6fa76dc8d0133181dd65e6614d5fb1220d671d67b0124aef7d97dc02d7e342ab143a47779d"; };
"@jridgewell/trace-mapping@npm:0.3.9" = { filename = "@jridgewell-trace-mapping-npm-0.3.9-91625cd7fb-d89597752f.zip"; sha512 = "d89597752fd88d3f3480845691a05a44bd21faac18e2185b6f436c3b0fd0c5a859fbbd9aaa92050c4052caf325ad3e10e2e1d1b64327517471b7d51babc0ddef"; };
"path-parse@npm:1.0.7" = { filename = "path-parse-npm-1.0.7-09564527b7-49abf3d811.zip"; sha512 = "49abf3d81115642938a8700ec580da6e830dde670be21893c62f4e10bd7dd4c3742ddc603fe24f898cba7eb0c6bc1777f8d9ac14185d34540c6d4d80cd9cae8a"; };
"supports-preserve-symlinks-flag@npm:1.0.0" = { filename = "supports-preserve-symlinks-flag-npm-1.0.0-f17c4d0028-53b1e247e6.zip"; sha512 = "53b1e247e68e05db7b3808b99b892bd36fb096e6fba213a06da7fab22045e97597db425c724f2bbd6c99a3c295e1e73f3e4de78592289f38431049e1277ca0ae"; };
"globby@npm:11.1.0" = { filename = "globby-npm-11.1.0-bdcdf20c71-b4be8885e0.zip"; sha512 = "b4be8885e0cfa018fc783792942d53926c35c50b3aefd3fdcfb9d22c627639dc26bd2327a40a0b74b074100ce95bb7187bfeae2f236856aa3de183af7a02aea6"; };
"printj@npm:1.1.2" = { filename = "printj-npm-1.1.2-5c18cf1e70-1c0c668445.zip"; sha512 = "1c0c66844545415e339356ad62009cdc467819817b1e0341aba428087a1414d46b84089edb4e77ef24705829f8aae6349724b9c7bd89d8690302b2de7a89b315"; };
"commander@npm:2.20.3" = { filename = "commander-npm-2.20.3-d8dcbaa39b-ab8c07884e.zip"; sha512 = "ab8c07884e42c3a8dbc5dd9592c606176c7eb5c1ca5ff274bcf907039b2c41de3626f684ea75ccf4d361ba004bbaff1f577d5384c155f3871e456bdf27becf9e"; };
"commander@npm:2.14.1" = { filename = "commander-npm-2.14.1-c6046110cb-26bd49febe.zip"; sha512 = "26bd49febeac8efabb7488fb5a4a2480b04bc4c4eef3c50da93eead72959f7a5232d003deda5b9761937205721274e80108f6d1d2b45ae7a8387cfb92031084e"; };
"@types/json5@npm:0.0.29" = { filename = "@types-json5-npm-0.0.29-f63a7916bd-e60b153664.zip"; sha512 = "e60b153664572116dfea673c5bda7778dbff150498f44f998e34b5886d8afc47f16799280e4b6e241c0472aef1bc36add771c569c68fc5125fc2ae519a3eb9ac"; };
"minimist@npm:1.2.6" = { filename = "minimist-npm-1.2.6-f4cee4b4af-d15428cd1e.zip"; sha512 = "d15428cd1e11eb14e1233bcfb88ae07ed7a147de251441d61158619dfb32c4d7e9061d09cab4825fdee18ecd6fce323228c8c47b5ba7cd20af378ca4048fb3fb"; };
"strip-bom@npm:3.0.0" = { filename = "strip-bom-npm-3.0.0-71e8f81ff9-8d50ff27b7.zip"; sha512 = "8d50ff27b7ebe5ecc78f1fe1e00fcdff7af014e73cf724b46fb81ef889eeb1015fc5184b64e81a2efe002180f3ba431bdd77e300da5c6685d702780fbf0c8d5b"; };
"type-fest@npm:0.8.1" = { filename = "type-fest-npm-0.8.1-351ad028fe-d61c4b2eba.zip"; sha512 = "d61c4b2eba24009033ae4500d7d818a94fd6d1b481a8111612ee141400d5f1db46f199c014766b9fa9b31a6a7374d96fc748c6d688a78a3ce5a33123839becb7"; };
"es-shim-unscopables@npm:1.0.0" = { filename = "es-shim-unscopables-npm-1.0.0-06186593f1-83e95cadbb.zip"; sha512 = "83e95cadbb6ee44d3644dfad60dcad7929edbc42c85e66c3e99aefd68a3a5c5665f2686885cddb47dfeabfd77bd5ea5a7060f2092a955a729bbd8834f0d86fa1"; };
"call-bind@npm:1.0.2" = { filename = "call-bind-npm-1.0.2-c957124861-f8e31de9d1.zip"; sha512 = "f8e31de9d19988a4b80f3e704788c4a2d6b6f3d17cfec4f57dc29ced450c53a49270dc66bf0fbd693329ee948dd33e6c90a329519aef17474a4d961e8d6426b0"; };
"define-properties@npm:1.1.4" = { filename = "define-properties-npm-1.1.4-85ee575655-ce0aef3f9e.zip"; sha512 = "ce0aef3f9eb193562b5cfb79b2d2c86b6a109dfc9fdcb5f45d680631a1a908c06824ddcdb72b7573b54e26ace07f0a23420aaba0d5c627b34d2c1de8ef527e2b"; };
"json5@npm:1.0.1" = { filename = "json5-npm-1.0.1-647fc8794b-e76ea23dbb.zip"; sha512 = "e76ea23dbb8fc1348c143da628134a98adf4c5a4e8ea2adaa74a80c455fc2cdf0e2e13e6398ef819bfe92306b610ebb2002668ed9fc1af386d593691ef346fc3"; };
"http-cache-semantics@npm:4.1.0" = { filename = "http-cache-semantics-npm-4.1.0-860520a31f-974de94a81.zip"; sha512 = "974de94a81c5474be07f269f9fd8383e92ebb5a448208223bfb39e172a9dbc26feff250192ecc23b9593b3f92098e010406b0f24bd4d588d631f80214648ed42"; };
"normalize-url@npm:6.1.0" = { filename = "normalize-url-npm-6.1.0-b95bc12ece-4a49446311.zip"; sha512 = "4a4944631173e7d521d6b80e4c85ccaeceb2870f315584fa30121f505a6dfd86439c5e3fdd8cd9e0e291290c41d0c3599f0cb12ab356722ed242584c30348e50"; };
"buffer-from@npm:1.1.2" = { filename = "buffer-from-npm-1.1.2-03d2f20d7e-0448524a56.zip"; sha512 = "0448524a562b37d4d7ed9efd91685a5b77a50672c556ea254ac9a6d30e3403a517d8981f10e565db24e8339413b43c97ca2951f10e399c6125a0d8911f5679bb"; };
"inherits@npm:2.0.4" = { filename = "inherits-npm-2.0.4-c66b3957a0-4a48a73384.zip"; sha512 = "4a48a733847879d6cf6691860a6b1e3f0f4754176e4d71494c41f3475553768b10f84b5ce1d40fbd0e34e6bfbb864ee35858ad4dd2cf31e02fc4a154b724d7f1"; };
"typedarray@npm:0.0.6" = { filename = "typedarray-npm-0.0.6-37638b2241-33b39f3d0e.zip"; sha512 = "33b39f3d0e8463985eeaeeacc3cb2e28bc3dfaf2a5ed219628c0b629d5d7b810b0eb2165f9f607c34871d5daa92ba1dc69f49051cf7d578b4cbd26c340b9d1b1"; };
"@typescript-eslint/typescript-estree@npm:5.38.1" = { filename = "@typescript-eslint-typescript-estree-npm-5.38.1-139af46521-ec73496f73.zip"; sha512 = "ec73496f73bd7f97d1585d25484874f092141a5f92ade7bd324fb76ef52888f0d77cc4375bdecc92cc3bacf5d61d65197acbb9af4fd9322b51db286c68a320c6"; };
"path-exists@npm:3.0.0" = { filename = "path-exists-npm-3.0.0-e80371aa68-96e92643aa.zip"; sha512 = "96e92643aa34b4b28d0de1cd2eba52a1c5313a90c6542d03f62750d82480e20bfa62bc865d5cfc6165f5fcd5aeb0851043c40a39be5989646f223300021bae0a"; };
"is-string@npm:1.0.7" = { filename = "is-string-npm-1.0.7-9f7066daed-323b3d0462.zip"; sha512 = "323b3d04622f78d45077cf89aab783b2f49d24dc641aa89b5ad1a72114cfeff2585efc8c12ef42466dff32bde93d839ad321b26884cf75e5a7892a938b089989"; };
"ms@npm:2.1.3" = { filename = "ms-npm-2.1.3-81ff3cfac1-aa92de6080.zip"; sha512 = "aa92de608021b242401676e35cfa5aa42dd70cbdc082b916da7fb925c542173e36bce97ea3e804923fe92c0ad991434e4a38327e15a1b5b5f945d66df615ae6d"; };
"find-up@npm:4.1.0" = { filename = "find-up-npm-4.1.0-c3ccf8d855-4c172680e8.zip"; sha512 = "4c172680e8f8c1f78839486e14a43ef82e9decd0e74145f40707cc42e7420506d5ec92d9a11c22bd2c48fb0c384ea05dd30e10dd152fefeec6f2f75282a8b844"; };
"clone-response@npm:1.0.3" = { filename = "clone-response-npm-1.0.3-f71cb6aff5-4e671cac39.zip"; sha512 = "4e671cac39b11c60aa8ba0a450657194a5d6504df51bca3fac5b3bd0145c4f8e8464898f87c8406b83232e3bc5cca555f51c1f9c8ac023969ebfbf7f6bdabb2e"; };
"get-stream@npm:5.2.0" = { filename = "get-stream-npm-5.2.0-2cfd3b452b-8bc1a23174.zip"; sha512 = "8bc1a23174a06b2b4ce600df38d6c98d2ef6d84e020c1ddad632ad75bac4e092eeb40e4c09e0761c35fc2dbc5e7fff5dab5e763a383582c4a167dd69a905bd12"; };
"keyv@npm:4.5.0" = { filename = "keyv-npm-4.5.0-57560bec53-d294873cf8.zip"; sha512 = "d294873cf88ec8f691e5edeb7b4b884f886c5f021a01902a0e243c362449db2b55419d7fb7187d059add747b7398321e39e44d391b65f94935174ce13452714d"; };
"estraverse@npm:4.3.0" = { filename = "estraverse-npm-4.3.0-920a32f3c6-a6299491f9.zip"; sha512 = "a6299491f9940bb246124a8d44b7b7a413a8336f5436f9837aaa9330209bd9ee8af7e91a654a3545aee9c54b3308e78ee360cef1d777d37cfef77d2fa33b5827"; };
"deepmerge@npm:2.2.1" = { filename = "deepmerge-npm-2.2.1-44c00cbffa-284b710650.zip"; sha512 = "284b71065079e66096229f735a9a0222463c9ca9ee9dda7d5e9a0545bf254906dbc7377e3499ca3b2212073672b1a430d80587993b43b87d8de17edc6af649a8"; };
"get-stdin@npm:5.0.1" = { filename = "get-stdin-npm-5.0.1-6b29b9ed95-f9784638ad.zip"; sha512 = "f9784638ad3e68a0a8bdc031aedf0fca749843cd134956fbd4f3bbac17c359e0fb9210343fcbed72ee79fb19d8e4c49b7a6e742cc5d44e94ac1405e9371d4b3e"; };
"pipe-functions@npm:1.3.0" = { filename = "pipe-functions-npm-1.3.0-40aa57e7ee-eab555b488.zip"; sha512 = "eab555b4886bc37272f2d30e8cb8650833af184a06cb637072f42b24872c438624facc7a910813ed2889e02cf9f92ef5b0e5081957f64878808cf0acf9c3e4e0"; };
"p-locate@npm:2.0.0" = { filename = "p-locate-npm-2.0.0-3a2ee263dd-e2dceb9b49.zip"; sha512 = "e2dceb9b49b96d5513d90f715780f6f4972f46987dc32a0e18bc6c3fc74a1a5d73ec5f81b1398af5e58b99ea1ad03fd41e9181c01fa81b4af2833958696e3081"; };
"inspect-function@npm:0.3.4" = { filename = "inspect-function-npm-0.3.4-dc6dd04c98-11fd23f101.zip"; sha512 = "11fd23f101ed52258728514b4e325116761efca77bed217925afd8aebb3a54ed9c2c252cddbef14341159f1a2037c8b9a703fd9dd82aeb263034afba70cf1825"; };
"balanced-match@npm:1.0.2" = { filename = "balanced-match-npm-1.0.2-a53c126459-9706c088a2.zip"; sha512 = "9706c088a283058a8a99e0bf91b0a2f75497f185980d9ffa8b304de1d9e58ebda7c72c07ebf01dadedaac5b2907b2c6f566f660d62bd336c3468e960403b9d65"; };
"concat-map@npm:0.0.1" = { filename = "concat-map-npm-0.0.1-85a921b7ee-902a9f5d89.zip"; sha512 = "902a9f5d8967a3e2faf138d5cb784b9979bad2e6db5357c5b21c568df4ebe62bcb15108af1b2253744844eb964fc023fbd9afbbbb6ddd0bcc204c6fb5b7bf3af"; };
"@jridgewell/resolve-uri@npm:3.1.0" = { filename = "@jridgewell-resolve-uri-npm-3.1.0-6ff2351e61-b5ceaaf9a1.zip"; sha512 = "b5ceaaf9a110fcb2780d1d8f8d4a0bfd216702f31c988d8042e5f8fbe353c55d9b0f55a1733afdc64806f8e79c485d2464680ac48a0d9fcadb9548ee6b81d267"; };
"@jridgewell/sourcemap-codec@npm:1.4.14" = { filename = "@jridgewell-sourcemap-codec-npm-1.4.14-f5f0630788-61100637b6.zip"; sha512 = "61100637b6d173d3ba786a5dff019e1a74b1f394f323c1fee337ff390239f053b87266c7a948777f4b1ee68c01a8ad0ab61e5ff4abb5a012a0b091bec391ab97"; };
"esrecurse@npm:4.3.0" = { filename = "esrecurse-npm-4.3.0-10b86a887a-ebc17b1a33.zip"; sha512 = "ebc17b1a33c51cef46fdc28b958994b1dc43cd2e86237515cbc3b4e5d2be6a811b2315d0a1a4d9d340b6d2308b15322f5c8291059521cc5f4802f65e7ec32837"; };
"array-union@npm:2.1.0" = { filename = "array-union-npm-2.1.0-4e4852b221-5bee12395c.zip"; sha512 = "5bee12395cba82da674931df6d0fea23c4aa4660cb3b338ced9f828782a65caa232573e6bf3968f23e0c5eb301764a382cef2f128b170a9dc59de0e36c39f98d"; };
"merge2@npm:1.4.1" = { filename = "merge2-npm-1.4.1-a2507bd06c-7268db63ed.zip"; sha512 = "7268db63ed5169466540b6fb947aec313200bcf6d40c5ab722c22e242f651994619bcd85601602972d3c85bd2cc45a358a4c61937e9f11a061919a1da569b0c2"; };
"slash@npm:3.0.0" = { filename = "slash-npm-3.0.0-b87de2279a-94a93fff61.zip"; sha512 = "94a93fff615f25a999ad4b83c9d5e257a7280c90a32a7cb8b4a87996e4babf322e469c42b7f649fd5796edd8687652f3fb452a86dc97a816f01113183393f11c"; };
"strip-ansi@npm:4.0.0" = { filename = "strip-ansi-npm-4.0.0-d4de985014-d9186e6c0c.zip"; sha512 = "d9186e6c0cf78f25274f6750ee5e4a5725fb91b70fdd79aa5fe648eab092a0ec5b9621b22d69d4534a56319f75d8944efbd84e3afa8d4ad1b9a9491f12c84eca"; };
"yargs-parser@npm:7.0.0" = { filename = "yargs-parser-npm-7.0.0-ad505519f5-af411d1448.zip"; sha512 = "af411d144801c374f059b9f955976891cf4ec0c0f721516a232ba0c6df59cdb2b05a5ed306aa228fdeee1da2103cd4c335e2e9c3e0d82d15477b33e6479c027c"; };
"get-intrinsic@npm:1.1.3" = { filename = "get-intrinsic-npm-1.1.3-b6c7bd1010-152d79e872.zip"; sha512 = "152d79e87251d536cf880ba75cfc3d6c6c50e12b3a64e1ea960e73a3752b47c69f46034456eae1b0894359ce3bc64c55c186f2811f8a788b75b638b06fab228a"; };
"read-pkg@npm:5.2.0" = { filename = "read-pkg-npm-5.2.0-50426bd8dc-eb696e6052.zip"; sha512 = "eb696e60528b29aebe10e499ba93f44991908c57d70f2d26f369e46b8b9afc208ef11b4ba64f67630f31df8b6872129e0a8933c8c53b7b4daf0eace536901222"; };
"readable-stream@npm:3.6.0" = { filename = "readable-stream-npm-3.6.0-23a4a5eb56-d4ea81502d.zip"; sha512 = "d4ea81502d3799439bb955a3a5d1d808592cf3133350ed352aeaa499647858b27b1c4013984900238b0873ec8d0d8defce72469fb7a83e61d53f5ad61cb80dc8"; };
"dir-glob@npm:3.0.1" = { filename = "dir-glob-npm-3.0.1-1aea628b1b-fa05e18324.zip"; sha512 = "fa05e18324510d7283f55862f3161c6759a3f2f8dbce491a2fc14c8324c498286c54282c1f0e933cb930da8419b30679389499b919122952a4f8592362ef4615"; };
"object-keys@npm:1.1.1" = { filename = "object-keys-npm-1.1.1-1bf2f1be93-b363c5e764.zip"; sha512 = "b363c5e7644b1e1b04aa507e88dcb8e3a2f52b6ffd0ea801e4c7a62d5aa559affe21c55a07fd4b1fd55fc03a33c610d73426664b20032405d7b92a1414c34d6a"; };
"has-property-descriptors@npm:1.0.0" = { filename = "has-property-descriptors-npm-1.0.0-56289b918d-a6d3f0a266.zip"; sha512 = "a6d3f0a266d0294d972e354782e872e2fe1b6495b321e6ef678c9b7a06a40408a6891817350c62e752adced73a94ac903c54734fee05bf65b1905ee1368194bb"; };
"path-exists@npm:4.0.0" = { filename = "path-exists-npm-4.0.0-e9e4f63eb0-505807199d.zip"; sha512 = "505807199dfb7c50737b057dd8d351b82c033029ab94cb10a657609e00c1bc53b951cfdbccab8de04c5584d5eff31128ce6afd3db79281874a5ef2adbba55ed1"; };
"mimic-response@npm:1.0.1" = { filename = "mimic-response-npm-1.0.1-f6f85dde84-034c78753b.zip"; sha512 = "034c78753b0e622bc03c983663b1cdf66d03861050e0c8606563d149bc2b02d63f62ce4d32be4ab50d0553ae0ffe647fc34d1f5281184c6e1e8cf4d85e8d9823"; };
"json-buffer@npm:3.0.1" = { filename = "json-buffer-npm-3.0.1-f8f6d20603-9026b03edc.zip"; sha512 = "9026b03edc2847eefa2e37646c579300a1f3a4586cfb62bf857832b60c852042d0d6ae55d1afb8926163fa54c2b01d83ae24705f34990348bdac6273a29d4581"; };
"command-line-usage@npm:4.1.0" = { filename = "command-line-usage-npm-4.1.0-3aef41faeb-8283146c9d.zip"; sha512 = "8283146c9d1b9fb71577efcd2c813a8da0627d0edf38578de7433064dbeaa0befc518297c19839b4fa1f1b512fee2684f8874a3729203870eafa945aa9c40052"; };
"inspect-parameters-declaration@npm:0.0.9" = { filename = "inspect-parameters-declaration-npm-0.0.9-418a0cdff5-ec6573bb96.zip"; sha512 = "ec6573bb969a5bcbd6492b8c1b8c081b069d8dfd53da9499448e73fafbcc5b3605822d9d7577c6f3b92ddab47e6556abb7dd8243ac8fddc2b991d12afbb2f93b"; };
"split-skip@npm:0.0.1" = { filename = "split-skip-npm-0.0.1-936bdd792e-6c7c1dd5ec.zip"; sha512 = "6c7c1dd5ec396a25b039a1047915ee5ae7276cc3384485f72fe4069f38ab9514d647761132cb8b86eeb5e12d26e44e4669bddd886a4eeaa369bcbb19e50066a0"; };
"unpack-string@npm:0.0.2" = { filename = "unpack-string-npm-0.0.2-ed3ba1a965-a320ae1620.zip"; sha512 = "a320ae1620a646779c9049f31f2b7403bb24921dda6296922dee45bfdf03fdb925dbacff65c702f66cef98e28f61d5ac7c15614dbdffe69d2413bfd50ab12df7"; };
"has-tostringtag@npm:1.0.0" = { filename = "has-tostringtag-npm-1.0.0-b1fcf3ab55-cc12eb28cb.zip"; sha512 = "cc12eb28cb6ae22369ebaad3a8ab0799ed61270991be88f208d508076a1e99abe4198c965935ce85ea90b60c94ddda73693b0920b58e7ead048b4a391b502c1c"; };
"locate-path@npm:5.0.0" = { filename = "locate-path-npm-5.0.0-46580c43e4-83e51725e6.zip"; sha512 = "83e51725e67517287d73e1ded92b28602e3ae5580b301fe54bfb76c0c723e3f285b19252e375712316774cf52006cb236aed5704692c32db0d5d089b69696e30"; };
"object-to-arguments@npm:0.0.8" = { filename = "object-to-arguments-npm-0.0.8-4a2b0f62f1-4a655e455b.zip"; sha512 = "4a655e455b943a6f7f4160b9f10b53eb174fcb44a6b8f51aac374eb8b0d34a46d28c038688b395735393bd12dbeca1542d15d3e634659bd1872c285ed97a325f"; };
"ansi-regex@npm:3.0.1" = { filename = "ansi-regex-npm-3.0.1-01f44078a3-09daf180c5.zip"; sha512 = "09daf180c5f59af9850c7ac1bd7fda85ba596cc8cbeb210826e90755f06c818af86d9fa1e6e8322fab2c3b9e9b03f56c537b42241139f824dd75066a1e7257cc"; };
"camelcase@npm:4.1.0" = { filename = "camelcase-npm-4.1.0-6903b265cd-9683356daf.zip"; sha512 = "9683356daf9b64fae4b30c91f8ceb1f34f22746e03d1804efdbe738357d38b47f206cdd71efcf2ed72018b2e88eeb8ec3f79adb09c02f1253a4b6d5d405ff2ae"; };
"p-limit@npm:1.3.0" = { filename = "p-limit-npm-1.3.0-fdb471d864-281c1c0b8c.zip"; sha512 = "281c1c0b8c82e1ac9f81acd72a2e35d402bf572e09721ce5520164e9de07d8274451378a3470707179ad13240535558f4b277f02405ad752e08c7d5b0d54fbfd"; };
"has-symbols@npm:1.0.3" = { filename = "has-symbols-npm-1.0.3-1986bff2c4-a054c40c63.zip"; sha512 = "a054c40c631c0d5741a8285010a0777ea0c068f99ed43e5d6eb12972da223f8af553a455132fdb0801bdcfa0e0f443c0c03a68d8555aa529b3144b446c3f2410"; };
"resolve@patch:resolve@npm%3A1.22.1#~builtin<compat/resolve>::version=1.22.1&hash=07638b" = { filename = "resolve-patch-46f9469d0d-5656f4d0be.zip"; sha512 = "5656f4d0bedcf8eb52685c1abdf8fbe73a1603bb1160a24d716e27a57f6cecbe2432ff9c89c2bd57542c3a7b9d14b1882b73bfe2e9d7849c9a4c0b8b39f02b8b"; };
"@types/normalize-package-data@npm:2.4.1" = { filename = "@types-normalize-package-data-npm-2.4.1-c31c56ae6a-e87bccbf11.zip"; sha512 = "e87bccbf11f95035c89a132b52b79ce69a1e3652fe55962363063c9c0dae0fe2477ebc585e03a9652adc6f381d24ba5589cc5e51849df4ced3d3e004a7d40ed5"; };
"type-fest@npm:0.6.0" = { filename = "type-fest-npm-0.6.0-76b229965b-b2188e6e4b.zip"; sha512 = "b2188e6e4b21557f6e92960ec496d28a51d68658018cba8b597bd3ef757721d1db309f120ae987abeeda874511d14b776157ff809f23c6d1ce8f83b9b2b7d60f"; };
"pump@npm:3.0.0" = { filename = "pump-npm-3.0.0-0080bf6a7a-e42e9229fb.zip"; sha512 = "e42e9229fba14732593a718b04cb5e1cfef8254544870997e0ecd9732b189a48e1256e4e5478148ecb47c8511dca2b09eae56b4d0aad8009e6fac8072923cfc9"; };
"util-deprecate@npm:1.0.2" = { filename = "util-deprecate-npm-1.0.2-e3fe1a219c-474acf1146.zip"; sha512 = "474acf1146cb2701fe3b074892217553dfcf9a031280919ba1b8d651a068c9b15d863b7303cb15bd00a862b498e6cf4ad7b4a08fb134edd5a6f7641681cb54a2"; };
"path-type@npm:4.0.0" = { filename = "path-type-npm-4.0.0-10d47fc86a-5b1e2daa24.zip"; sha512 = "5b1e2daa247062061325b8fdbfd1fb56dde0a448fb1455453276ea18c60685bdad23a445dc148cf87bc216be1573357509b7d4060494a6fd768c7efad833ee45"; };
"fast-glob@npm:3.2.12" = { filename = "fast-glob-npm-3.2.12-162763bbae-0b1990f6ce.zip"; sha512 = "0b1990f6ce831c7e28c4d505edcdaad8e27e88ab9fa65eedadb730438cfc7cde4910d6c975d6b7b8dc8a73da4773702ebcfcd6e3518e73938bb1383badfe01c2"; };
"stringify-parameters@npm:0.0.4" = { filename = "stringify-parameters-npm-0.0.4-6be083f9bf-e66dd0e41e.zip"; sha512 = "e66dd0e41e4e9952d9c8eccd0e5817c738a5a789cdbfd756a0a3eeac0920191aa4559d1e30dad73fc6efac87a1616bc198217f85f886c1b923f442841a6a7b33"; };
"string_decoder@npm:1.3.0" = { filename = "string_decoder-npm-1.3.0-2422117fd0-8417646695.zip"; sha512 = "8417646695a66e73aefc4420eb3b84cc9ffd89572861fe004e6aeb13c7bc00e2f616247505d2dbbef24247c372f70268f594af7126f43548565c68c117bdeb56"; };
"eslint@npm:8.19.0" = { filename = "eslint-npm-8.19.0-147f1e0c86-0bc9df1a3a.zip"; sha512 = "0bc9df1a3a09dcd5a781ec728f280aa8af3ab19c2d1f14e2668b5ee5b8b1fb0e72dde5c3acf738e7f4281685fb24ec149b6154255470b06cf41de76350bca7a4"; };
"typical@npm:2.6.1" = { filename = "typical-npm-2.6.1-25fd0ac6b5-6af04fefe5.zip"; sha512 = "6af04fefe50d90d3471f058b2cdc0f49b7436bdd605cd00acea7965926ff388a5a7d692ef144f45fccee6f8e896c065702ecc44b69057e2ce88c09e897c7d3a4"; };
"split-skip@npm:0.0.2" = { filename = "split-skip-npm-0.0.2-34b0cf4422-d1099afb18.zip"; sha512 = "d1099afb18b4558cb744289aa6daa0f3a5f06d986e1171bb1a4dac5ab8c977228d441e597489568f988d0e0d474dd2dcb7857ec443b4e0d1f815324564732793"; };
"inspect-parameters-declaration@npm:0.0.8" = { filename = "inspect-parameters-declaration-npm-0.0.8-86b063914a-8a493042fc.zip"; sha512 = "8a493042fce5b6e16e49cbccc6d33cfeb39a7a09057ff4a2b4e6743ee904d61466096b7e05d0d24f75302983f4ae81bc35a7a557181e3bfdea41bad12067b4bf"; };
"ansi-escape-sequences@npm:4.1.0" = { filename = "ansi-escape-sequences-npm-4.1.0-b006e3457c-709982bd66.zip"; sha512 = "709982bd669d37f5e4a698e10cd9c860c8e69b580ec3a62494afcb635bdcb9312ec5ee97c1e943445af96dc42e0ab5832cf31a904101c3fe7414aad42f27e348"; };
"array-back@npm:2.0.0" = { filename = "array-back-npm-2.0.0-3366a86d25-ab36ab3504.zip"; sha512 = "ab36ab3504b25116b47541fb0ac78ff13d1e991f33d98c361edd3aada3ed818a900b619bd67b195dd4e41b9256c27e8cdd6a69ece507e482f1207d07670ed6bd"; };
"p-try@npm:1.0.0" = { filename = "p-try-npm-1.0.0-7373139e40-3b5303f77e.zip"; sha512 = "3b5303f77eb7722144154288bfd96f799f8ff3e2b2b39330efe38db5dd359e4fb27012464cd85cb0a76e9b7edd1b443568cb3192c22e7cffc34989df0bafd605"; };
"p-locate@npm:4.1.0" = { filename = "p-locate-npm-4.1.0-eec6872537-513bd14a45.zip"; sha512 = "513bd14a455f5da4ebfcb819ef706c54adb09097703de6aeaa5d26fe5ea16df92b48d1ac45e01e3944ce1e6aa2a66f7f8894742b8c9d6e276e16cd2049a2b870"; };
"normalize-package-data@npm:2.5.0" = { filename = "normalize-package-data-npm-2.5.0-af0345deed-7999112efc.zip"; sha512 = "7999112efc35a6259bc22db460540cae06564aa65d0271e3bdfa86876d08b0e578b7b5b0028ee61b23f1cae9fc0e7847e4edc0948d3068a39a2a82853efc8499"; };
"parse-json@npm:5.2.0" = { filename = "parse-json-npm-5.2.0-00a63b1199-62085b17d6.zip"; sha512 = "62085b17d64da57f40f6afc2ac1f4d95def18c4323577e1eced571db75d9ab59b297d1d10582920f84b15985cbfc6b6d450ccbf317644cfa176f3ed982ad87e2"; };
"@nodelib/fs.stat@npm:2.0.5" = { filename = "@nodelib-fs.stat-npm-2.0.5-01f4dd3030-012480b5ca.zip"; sha512 = "012480b5ca9d97bff9261571dbbec7bbc6033f69cc92908bc1ecfad0792361a5a1994bc48674b9ef76419d056a03efadfce5a6cf6dbc0a36559571a7a483f6f0"; };
"end-of-stream@npm:1.4.4" = { filename = "end-of-stream-npm-1.4.4-497fc6dee1-530a5a5a1e.zip"; sha512 = "530a5a5a1e517e962854a31693dbb5c0b2fc40b46dad2a56a2deec656ca040631124f4795823acc68238147805f8b021abbe221f4afed5ef3c8e8efc2024908b"; };
"once@npm:1.4.0" = { filename = "once-npm-1.4.0-ccf03ef07a-cd0a885013.zip"; sha512 = "cd0a88501333edd640d95f0d2700fbde6bff20b3d4d9bdc521bdd31af0656b5706570d6c6afe532045a20bb8dc0849f8332d6f2a416e0ba6d3d3b98806c7db68"; };
"safe-buffer@npm:5.2.1" = { filename = "safe-buffer-npm-5.2.1-3481c8aa9b-b99c4b41fd.zip"; sha512 = "b99c4b41fdd67a6aaf280fcd05e9ffb0813654894223afb78a31f14a19ad220bba8aba1cb14eddce1fcfb037155fe6de4e861784eb434f7d11ed58d1e70dd491"; };
"glob-parent@npm:5.1.2" = { filename = "glob-parent-npm-5.1.2-021ab32634-f4f2bfe242.zip"; sha512 = "f4f2bfe2425296e8a47e36864e4f42be38a996db40420fe434565e4480e3322f18eb37589617a98640c5dc8fdec1a387007ee18dbb1f3f5553409c34d17f425e"; };
"escape-string-regexp@npm:4.0.0" = { filename = "escape-string-regexp-npm-4.0.0-4b531d8d59-98b48897d9.zip"; sha512 = "98b48897d93060f2322108bf29db0feba7dd774be96cd069458d1453347b25ce8682ecc39859d4bca2203cc0ab19c237bcc71755eff49a0f8d90beadeeba5cc5"; };
"fast-deep-equal@npm:3.1.3" = { filename = "fast-deep-equal-npm-3.1.3-790edcfcf5-e21a9d8d84.zip"; sha512 = "e21a9d8d84f53493b6aa15efc9cfd53dd5b714a1f23f67fb5dc8f574af80df889b3bce25dc081887c6d25457cce704e636395333abad896ccdec03abaf1f3f9d"; };
"functional-red-black-tree@npm:1.0.1" = { filename = "functional-red-black-tree-npm-1.0.1-ccfe924dcd-ca6c170f37.zip"; sha512 = "ca6c170f37640e2d94297da8bb4bf27a1d12bea3e00e6a3e007fd7aa32e37e000f5772acf941b4e4f3cf1c95c3752033d0c509af157ad8f526e7f00723b9eb9f"; };
"imurmurhash@npm:0.1.4" = { filename = "imurmurhash-npm-0.1.4-610c5068a0-7cae75c8cd.zip"; sha512 = "7cae75c8cd9a50f57dadd77482359f659eaebac0319dd9368bcd1714f55e65badd6929ca58569da2b6494ef13fdd5598cd700b1eba23f8b79c5f19d195a3ecf7"; };
"json-stable-stringify-without-jsonify@npm:1.0.1" = { filename = "json-stable-stringify-without-jsonify-npm-1.0.1-b65772b28b-cff44156dd.zip"; sha512 = "cff44156ddce9c67c44386ad5cddf91925fe06b1d217f2da9c4910d01f358c6e3989c4d5a02683c7a5667f9727ff05831f7aa8ae66c8ff691c556f0884d49215"; };
"lodash.merge@npm:4.6.2" = { filename = "lodash.merge-npm-4.6.2-77cb4416bf-ad580b4bdb.zip"; sha512 = "ad580b4bdbb7ca1f7abf7e1bce63a9a0b98e370cf40194b03380a46b4ed799c9573029599caebc1b14e3f24b111aef72b96674a56cfa105e0f5ac70546cdc005"; };
"natural-compare@npm:1.4.0" = { filename = "natural-compare-npm-1.4.0-97b75b362d-23ad088b08.zip"; sha512 = "23ad088b08f898fc9b53011d7bb78ec48e79de7627e01ab5518e806033861bef68d5b0cd0e2205c2f36690ac9571ff6bcb05eb777ced2eeda8d4ac5b44592c3d"; };
"strip-json-comments@npm:3.1.1" = { filename = "strip-json-comments-npm-3.1.1-dcb2324823-492f73e272.zip"; sha512 = "492f73e27268f9b1c122733f28ecb0e7e8d8a531a6662efbd08e22cccb3f9475e90a1b82cab06a392f6afae6d2de636f977e231296400d0ec5304ba70f166443"; };
"text-table@npm:0.2.0" = { filename = "text-table-npm-0.2.0-d92a778b59-b6937a38c8.zip"; sha512 = "b6937a38c80c7f84d9c11dd75e49d5c44f71d95e810a3250bd1f1797fc7117c57698204adf676b71497acc205d769d65c16ae8fa10afad832ae1322630aef10a"; };
"v8-compile-cache@npm:2.3.0" = { filename = "v8-compile-cache-npm-2.3.0-961375f150-adb0a271ea.zip"; sha512 = "adb0a271eaa2297f2f4c536acbfee872d0dd26ec2d76f66921aa7fc437319132773483344207bdbeee169225f4739016d8d2dbf0553913a52bb34da6d0334f8e"; };
"@nodelib/fs.walk@npm:1.2.8" = { filename = "@nodelib-fs.walk-npm-1.2.8-b4a89da548-190c643f15.zip"; sha512 = "190c643f156d8f8f277bf2a6078af1ffde1fd43f498f187c2db24d35b4b4b5785c02c7dc52e356497b9a1b65b13edc996de08de0b961c32844364da02986dc53"; };
"micromatch@npm:4.0.5" = { filename = "micromatch-npm-4.0.5-cfab5d7669-02a17b671c.zip"; sha512 = "02a17b671c06e8fefeeb6ef996119c1e597c942e632a21ef589154f23898c9c6a9858526246abb14f8bca6e77734aa9dcf65476fca47cedfb80d9577d52843fc"; };
"magicli@npm:0.0.5" = { filename = "magicli-npm-0.0.5-82bb79e8c5-563c655fd1.zip"; sha512 = "563c655fd14a92dfd4d606f3ebd97b20fc05e7b888b65aac58b79bea7e78f4051f58286f11f687f6deb9e4f4320ee9d8ba6f31645d4bb09d3d9dfa2b8f48ebdc"; };
"doctrine@npm:3.0.0" = { filename = "doctrine-npm-3.0.0-c6f1615f04-fd7673ca77.zip"; sha512 = "fd7673ca77fe26cd5cba38d816bc72d641f500f1f9b25b83e8ce28827fe2da7ad583a8da26ab6af85f834138cf8dae9f69b0cd6ab925f52ddab1754db44d99ce"; };
"file-entry-cache@npm:6.0.1" = { filename = "file-entry-cache-npm-6.0.1-31965cf0af-f49701feaa.zip"; sha512 = "f49701feaa6314c8127c3c2f6173cfefff17612f5ed2daaafc6da13b5c91fd43e3b2a58fd0d63f9f94478a501b167615931e7200e31485e320f74a33885a9c74"; };
"glob-parent@npm:6.0.2" = { filename = "glob-parent-npm-6.0.2-2cbef12738-c13ee97978.zip"; sha512 = "c13ee97978bef4f55106b71e66428eb1512e71a7466ba49025fc2aec59a5bfb0954d5abd58fc5ee6c9b076eef4e1f6d3375c2e964b88466ca390da4419a786a8"; };
"globals@npm:13.17.0" = { filename = "globals-npm-13.17.0-a6039e7d26-fbaf4112e5.zip"; sha512 = "fbaf4112e59b92c9f5575e85ce65e9e17c0b82711196ec5f58beb08599bbd92fd72703d6dfc9b080381fd35b644e1b11dcf25b38cc2341ec21df942594cbc8ce"; };
"js-yaml@npm:4.1.0" = { filename = "js-yaml-npm-4.1.0-3606f32312-c7830dfd45.zip"; sha512 = "c7830dfd456c3ef2c6e355cc5a92e6700ceafa1d14bba54497b34a99f0376cecbb3e9ac14d3e5849b426d5a5140709a66237a8c991c675431271c4ce5504151a"; };
"array-back@npm:3.1.0" = { filename = "array-back-npm-3.1.0-a52d25f5a3-7205004fcd.zip"; sha512 = "7205004fcd0f9edd926db921af901b083094608d5b265738d0290092f9822f73accb468e677db74c7c94ef432d39e5ed75a7b1786701e182efb25bbba9734209"; };
"table-layout@npm:0.4.5" = { filename = "table-layout-npm-0.4.5-1ffc9a985b-9642b67d1b.zip"; sha512 = "9642b67d1bb3d9ba85f2b95f0a65a12ec7e1186ce842c9be63f1fdf76e36e91be89955b58b7a16358e1b39a12ceb9860c41ed977d8305d792651c19f08e3f8f2"; };
"inspect-parameters-declaration@npm:0.0.10" = { filename = "inspect-parameters-declaration-npm-0.0.10-b077680d65-3f81940834.zip"; sha512 = "3f81940834d5bd229b9f6c2aa3c286271beb1c265a2865db57845efda0eff465ba377f8ddaa231251609184818af3fcac12722dbb1ac460b1ad48fbc0af77b76"; };
"hosted-git-info@npm:2.8.9" = { filename = "hosted-git-info-npm-2.8.9-62c44fa93f-c955394bda.zip"; sha512 = "c955394bdab888a1e9bb10eb33029e0f7ce5a2ac7b3f158099dc8c486c99e73809dca609f5694b223920ca2174db33d32b12f9a2a47141dc59607c29da5a62dd"; };
"semver@npm:5.7.1" = { filename = "semver-npm-5.7.1-40bcea106b-57fd0acfd0.zip"; sha512 = "57fd0acfd0bac382ee87cd52cd0aaa5af086a7dc8d60379dfe65fea491fb2489b6016400813930ecd61fd0952dae75c115287a1b16c234b1550887117744dfaf"; };
"json-parse-even-better-errors@npm:2.3.1" = { filename = "json-parse-even-better-errors-npm-2.3.1-144d62256e-798ed4cf33.zip"; sha512 = "798ed4cf3354a2d9ccd78e86d2169515a0097a5c133337807cdf7f1fc32e1391d207ccfc276518cc1d7d8d4db93288b8a50ba4293d212ad1336e52a8ec0a941f"; };
"lines-and-columns@npm:1.2.4" = { filename = "lines-and-columns-npm-1.2.4-d6c7cc5799-0c37f9f7fa.zip"; sha512 = "0c37f9f7fa212b38912b7145e1cd16a5f3cd34d782441c3e6ca653485d326f58b3caccda66efce1c5812bde4961bbde3374fae4b0d11bf1226152337f3894aa5"; };
"chalk@npm:4.1.2" = { filename = "chalk-npm-4.1.2-ba8b67ab80-fe75c9d5c7.zip"; sha512 = "fe75c9d5c76a7a98d45495b91b2172fa3b7a09e0cc9370e5c8feb1c567b85c4288e2b3fded7cfdd7359ac28d6b3844feb8b82b8686842e93d23c827c417e83fc"; };
"eslint-scope@npm:7.1.1" = { filename = "eslint-scope-npm-7.1.1-23935eb377-9f6e974ab2.zip"; sha512 = "9f6e974ab2db641ca8ab13508c405b7b859e72afe9f254e8131ff154d2f40c99ad4545ce326fd9fde3212ff29707102562a4834f1c48617b35d98c71a97fbf3e"; };
"import-fresh@npm:3.3.0" = { filename = "import-fresh-npm-3.3.0-3e34265ca9-2cacfad06e.zip"; sha512 = "2cacfad06e652b1edc50be650f7ec3be08c5e5a6f6d12d035c440a42a8cc028e60a5b99ca08a77ab4d6b1346da7d971915828f33cdab730d3d42f08242d09baa"; };
"levn@npm:0.4.1" = { filename = "levn-npm-0.4.1-d183b2d7bb-12c5021c85.zip"; sha512 = "12c5021c859bd0f5248561bf139121f0358285ec545ebf48bb3d346820d5c61a4309535c7f387ed7d84361cf821e124ce346c6b7cef8ee09a67c1473b46d0fc4"; };
"p-limit@npm:2.3.0" = { filename = "p-limit-npm-2.3.0-94a0310039-84ff17f1a3.zip"; sha512 = "84ff17f1a38126c3314e91ecfe56aecbf36430940e2873dadaa773ffe072dc23b7af8e46d4b6485d302a11673fe94c6b67ca2cfbb60c989848b02100d0594ac1"; };
"@babel/code-frame@npm:7.18.6" = { filename = "@babel-code-frame-npm-7.18.6-25229a7e34-195e2be317.zip"; sha512 = "195e2be3172d7684bf95cff69ae3b7a15a9841ea9d27d3c843662d50cdd7d6470fd9c8e64be84d031117e4a4083486effba39f9aef6bbb2c89f7f21bcfba33ba"; };
"error-ex@npm:1.3.2" = { filename = "error-ex-npm-1.3.2-5654f80c0f-c1c2b8b65f.zip"; sha512 = "c1c2b8b65f9c91b0f9d75f0debaa7ec5b35c266c2cac5de412c1a6de86d4cbae04ae44e510378cb14d032d0645a36925d0186f8bb7367bcc629db256b743a001"; };
"@humanwhocodes/config-array@npm:0.9.5" = { filename = "@humanwhocodes-config-array-npm-0.9.5-030a025eae-8ba6281bc0.zip"; sha512 = "8ba6281bc0590f6c6eadeefc14244b5a3e3f5903445aadd1a32099ed80e753037674026ce1b3c945ab93561bea5eb29e3c5bff67060e230c295595ba517a3492"; };
"cross-spawn@npm:7.0.3" = { filename = "cross-spawn-npm-7.0.3-e4ff3e65b3-671cc7c728.zip"; sha512 = "671cc7c7288c3a8406f3c69a3ae2fc85555c04169e9d611def9a675635472614f1c0ed0ef80955d5b6d4e724f6ced67f0ad1bb006c2ea643488fcfef994d7f52"; };
"espree@npm:9.4.0" = { filename = "espree-npm-9.4.0-0371ef3614-2e3020dde6.zip"; sha512 = "2e3020dde67892d2ba3632413b44d0dc31d92c29ce72267d7ec24216a562f0a6494d3696e2fa39a3ec8c0e0088d773947ab2925fbb716801a11eb8dd313ac89c"; };
"wrappy@npm:1.0.2" = { filename = "wrappy-npm-1.0.2-916de4d4b3-159da4805f.zip"; sha512 = "159da4805f7e84a3d003d8841557196034155008f817172d4e986bd591f74aa82aa7db55929a54222309e01079a65a92a9e6414da5a6aa4b01ee44a511ac3ee5"; };
"validate-npm-package-license@npm:3.0.4" = { filename = "validate-npm-package-license-npm-3.0.4-7af8adc7a8-35703ac889.zip"; sha512 = "35703ac889d419cf2aceef63daeadbe4e77227c39ab6287eeb6c1b36a746b364f50ba22e88591f5d017bc54685d8137bc2d328d0a896e4d3fd22093c0f32a9ad"; };
"ajv@npm:6.12.6" = { filename = "ajv-npm-6.12.6-4b5105e2b2-874972efe5.zip"; sha512 = "874972efe5c4202ab0a68379481fbd3d1b5d0a7bd6d3cc21d40d3536ebff3352a2a1fabb632d4fd2cc7fe4cbdcd5ed6782084c9bbf7f32a1536d18f9da5007d4"; };
"picomatch@npm:2.3.1" = { filename = "picomatch-npm-2.3.1-c782cfd986-050c865ce8.zip"; sha512 = "050c865ce81119c4822c45d3c84f1ced46f93a0126febae20737bd05ca20589c564d6e9226977df859ed5e03dc73f02584a2b0faad36e896936238238b0446cf"; };
"type-fest@npm:0.20.2" = { filename = "type-fest-npm-0.20.2-b36432617f-4fb3272df2.zip"; sha512 = "4fb3272df21ad1c552486f8a2f8e115c09a521ad7a8db3d56d53718d0c907b62c6e9141ba5f584af3f6830d0872c521357e512381f24f7c44acae583ad517d73"; };
"argparse@npm:2.0.1" = { filename = "argparse-npm-2.0.1-faff7999e6-83644b5649.zip"; sha512 = "83644b56493e89a254bae05702abf3a1101b4fa4d0ca31df1c9985275a5a5bd47b3c27b7fa0b71098d41114d8ca000e6ed90cad764b306f8a503665e4d517ced"; };
"fastq@npm:1.13.0" = { filename = "fastq-npm-1.13.0-a45963881c-32cf15c29a.zip"; sha512 = "32cf15c29afe622af187d12fc9cd93e160a0cb7c31a3bb6ace86b7dea3b28e7b72acde89c882663f307b2184e14782c6c664fa315973c03626c7d4bff070bb0b"; };
"braces@npm:3.0.2" = { filename = "braces-npm-3.0.2-782240b28a-e2a8e769a8.zip"; sha512 = "e2a8e769a863f3d4ee887b5fe21f63193a891c68b612ddb4b68d82d1b5f3ff9073af066c343e9867a393fe4c2555dcb33e89b937195feb9c1613d259edfcd459"; };
"deep-extend@npm:0.6.0" = { filename = "deep-extend-npm-0.6.0-e182924219-7be7e5a8d4.zip"; sha512 = "7be7e5a8d468d6b10e6a67c3de828f55001b6eb515d014f7aeb9066ce36bd5717161eb47d6a0f7bed8a9083935b465bc163ee2581c8b128d29bf61092fdf57a7"; };
"lodash.padend@npm:4.6.1" = { filename = "lodash.padend-npm-4.6.1-6a28392d72-c2e6e789de.zip"; sha512 = "c2e6e789debf83b98f5c085305cdcfff1067e7a31bda2a110fd765d3c11a99edfbeef570d9ef737ab3212006bdb8114e77622e518c18c1fce52b8fdfd9dab685"; };
"resolve-from@npm:4.0.0" = { filename = "resolve-from-npm-4.0.0-f758ec21bf-f4ba0b8494.zip"; sha512 = "f4ba0b8494846a5066328ad33ef8ac173801a51739eb4d63408c847da9a2e1c1de1e6cbbf72699211f3d13f8fc1325648b169bd15eb7da35688e30a5fb0e4a7f"; };
"prelude-ls@npm:1.2.1" = { filename = "prelude-ls-npm-1.2.1-3e4d272a55-cd192ec0d0.zip"; sha512 = "cd192ec0d0a8e4c6da3bb80e4f62afe336df3f76271ac6deb0e6a36187133b6073a19e9727a1ff108cd8b9982e4768850d413baa71214dd80c7979617dca827a"; };
"optionator@npm:0.9.1" = { filename = "optionator-npm-0.9.1-577e397aae-dbc6fa0656.zip"; sha512 = "dbc6fa065604b24ea57d734261914e697bd73b69eff7f18e967e8912aa2a40a19a9f599a507fa805be6c13c24c4eae8c71306c239d517d42d4c041c942f508a0"; };
"@nodelib/fs.scandir@npm:2.1.5" = { filename = "@nodelib-fs.scandir-npm-2.1.5-89c67370dd-a970d595bd.zip"; sha512 = "a970d595bd23c66c880e0ef1817791432dbb7acbb8d44b7e7d0e7a22f4521260d4a83f7f9fd61d44fda4610105577f8f58a60718105fb38352baed612fd79e59"; };
"inspect-function@npm:0.2.2" = { filename = "inspect-function-npm-0.2.2-6ce0425b3d-f5eeebde60.zip"; sha512 = "f5eeebde60a679e4bd419a7106deb901c85c51d7eb4ce2b32fec5cca182628866347bdbf1a6e02d03157534d69866c8166b7d103b5f05c093a615534c0ae825d"; };
"p-try@npm:2.2.0" = { filename = "p-try-npm-2.2.0-e0390dbaf8-f8a8e9a769.zip"; sha512 = "f8a8e9a7693659383f06aec604ad5ead237c7a261c18048a6e1b5b85a5f8a067e469aa24f5bc009b991ea3b058a87f5065ef4176793a200d4917349881216cae"; };
"is-arrayish@npm:0.2.1" = { filename = "is-arrayish-npm-0.2.1-23927dfb15-eef4417e3c.zip"; sha512 = "eef4417e3c10e60e2c810b6084942b3ead455af16c4509959a27e490e7aee87cfb3f38e01bbde92220b528a0ee1a18d52b787e1458ee86174d8c7f0e58cd488f"; };
"@humanwhocodes/object-schema@npm:1.2.1" = { filename = "@humanwhocodes-object-schema-npm-1.2.1-eb622b5d0e-a824a1ec31.zip"; sha512 = "a824a1ec31591231e4bad5787641f59e9633827d0a2eaae131a288d33c9ef0290bd16fda8da6f7c0fcb014147865d12118df10db57f27f41e20da92369fcb3f1"; };
"ansi-styles@npm:4.3.0" = { filename = "ansi-styles-npm-4.3.0-245c7d42c7-513b44c3b2.zip"; sha512 = "513b44c3b2105dd14cc42a19271e80f386466c4be574bccf60b627432f9198571ebf4ab1e4c3ba17347658f4ee1711c163d574248c0c1cdc2d5917a0ad582ec4"; };
"supports-color@npm:7.2.0" = { filename = "supports-color-npm-7.2.0-606bfcf7da-3dda818de0.zip"; sha512 = "3dda818de06ebbe5b9653e07842d9479f3555ebc77e9a0280caf5a14fb877ffee9ed57007c3b78f5a6324b8dbeec648d9e97a24e2ed9fdb81ddc69ea07100f4a"; };
"path-key@npm:3.1.1" = { filename = "path-key-npm-3.1.1-0e66ea8321-55cd7a9dd4.zip"; sha512 = "55cd7a9dd4b343412a8386a743f9c746ef196e57c823d90ca3ab917f90ab9f13dd0ded27252ba49dbdfcab2b091d998bc446f6220cd3cea65db407502a740020"; };
"acorn-jsx@npm:5.3.2" = { filename = "acorn-jsx-npm-5.3.2-d7594599ea-c3d3b2a89c.zip"; sha512 = "c3d3b2a89c9a056b205b69530a37b972b404ee46ec8e5b341666f9513d3163e2a4f214a71f4dfc7370f5a9c07472d2fd1c11c91c3f03d093e37637d95da98950"; };
"flat-cache@npm:3.0.4" = { filename = "flat-cache-npm-3.0.4-ee77e5911e-4fdd10ecbc.zip"; sha512 = "4fdd10ecbcbf7d520f9040dd1340eb5dfe951e6f0ecf2252edeec03ee68d989ec8b9a20f4434270e71bcfd57800dc09b3344fca3966b2eb8f613072c7d9a2365"; };
"parent-module@npm:1.0.1" = { filename = "parent-module-npm-1.0.1-1fae11b095-6ba8b25514.zip"; sha512 = "6ba8b255145cae9470cf5551eb74be2d22281587af787a2626683a6c20fbb464978784661478dd2a3f1dad74d1e802d403e1b03c1a31fab310259eec8ac560ff"; };
"type-check@npm:0.4.0" = { filename = "type-check-npm-0.4.0-60565800ce-ec688ebfc9.zip"; sha512 = "ec688ebfc9c45d0c30412e41ca9c0cdbd704580eb3a9ccf07b9b576094d7b86a012baebc95681999dd38f4f444afd28504cb3a89f2ef16b31d4ab61a0739025a"; };
"wordwrapjs@npm:3.0.0" = { filename = "wordwrapjs-npm-3.0.0-3ae3b50ec3-953322ec8d.zip"; sha512 = "953322ec8dd8b634a1a07a611760b0473e258073fd3bcab473082c6f0f30cdc48e641310209973d8557b9893bc291e32587f6dce05ea675242e21f8b0b0877bc"; };
"fast-json-stable-stringify@npm:2.1.0" = { filename = "fast-json-stable-stringify-npm-2.1.0-02e8905fda-b191531e36.zip"; sha512 = "b191531e36c607977e5b1c47811158733c34ccb3bfde92c44798929e9b4154884378536d26ad90dfecd32e1ffc09c545d23535ad91b3161a27ddbb8ebe0cbecb"; };
"json-schema-traverse@npm:0.4.1" = { filename = "json-schema-traverse-npm-0.4.1-4759091693-7486074d3b.zip"; sha512 = "7486074d3ba247769fda17d5181b345c9fb7d12e0da98b22d1d71a5db9698d8b4bd900a3ec1a4ffdd60846fc2556274a5c894d0c48795f14cb03aeae7b55260b"; };
"shebang-command@npm:2.0.0" = { filename = "shebang-command-npm-2.0.0-eb2b01921d-6b52fe8727.zip"; sha512 = "6b52fe87271c12968f6a054e60f6bde5f0f3d2db483a1e5c3e12d657c488a15474121a1d55cd958f6df026a54374ec38a4a963988c213b7570e1d51575cea7fa"; };
"which@npm:2.0.2" = { filename = "which-npm-2.0.2-320ddf72f7-1a5c563d3c.zip"; sha512 = "1a5c563d3c1b52d5f893c8b61afe11abc3bab4afac492e8da5bde69d550de701cf9806235f20a47b5c8fa8a1d6a9135841de2596535e998027a54589000e66d1"; };
"es-abstract@npm:1.20.3" = { filename = "es-abstract-npm-1.20.3-716a6119bf-225f24966e.zip"; sha512 = "225f24966ed960868bcfa7b39b38c9f4b68d1e0351e4e052a199e3e2fd93838a28b050687a0edf1021c20173d0831d076ff33ec581de77ca8aded67e2e138a80"; };
"@eslint/eslintrc@npm:1.3.2" = { filename = "@eslint-eslintrc-npm-1.3.2-fd8de37609-2074dca47d.zip"; sha512 = "2074dca47d7e1c5c6323ff353f690f4b25d3ab53fe7d27337e2592d37a894cf60ca0e85ca66b50ff2db0bc7e630cc1e9c7347d65bb185b61416565584c38999c"; };
"uri-js@npm:4.4.1" = { filename = "uri-js-npm-4.4.1-66d11cbcaf-7167432de6.zip"; sha512 = "7167432de6817fe8e9e0c9684f1d2de2bb688c94388f7569f7dbdb1587c9f4ca2a77962f134ec90be0cc4d004c939ff0d05acc9f34a0db39a3c797dada262633"; };
"reusify@npm:1.0.4" = { filename = "reusify-npm-1.0.4-95ac4aec11-c3076ebcc2.zip"; sha512 = "c3076ebcc22a6bc252cb0b9c77561795256c22b757f40c0d8110b1300723f15ec0fc8685e8d4ea6d7666f36c79ccc793b1939c748bf36f18f542744a4e379fcc"; };
"spdx-correct@npm:3.1.1" = { filename = "spdx-correct-npm-3.1.1-47f574c27a-77ce438344.zip"; sha512 = "77ce438344a34f9930feffa61be0eddcda5b55fc592906ef75621d4b52c07400a97084d8701557b13f7d2aae0cb64f808431f469e566ef3fe0a3a131dcb775a6"; };
"spdx-expression-parse@npm:3.0.1" = { filename = "spdx-expression-parse-npm-3.0.1-b718cbb35a-a1c6e104a2.zip"; sha512 = "a1c6e104a2cbada7a593eaa9f430bd5e148ef5290d4c0409899855ce8b1c39652bcc88a725259491a82601159d6dc790bedefc9016c7472f7de8de7361f8ccde"; };
"@babel/highlight@npm:7.18.6" = { filename = "@babel-highlight-npm-7.18.6-9d35ad2e27-92d8ee6154.zip"; sha512 = "92d8ee61549de5ff5120e945e774728e5ccd57fd3b2ed6eace020ec744823d4a98e242be1453d21764a30a14769ecd62170fba28539b211799bbaf232bbb2789"; };
"deep-is@npm:0.1.4" = { filename = "deep-is-npm-0.1.4-88938b5a67-edb65dd0d7.zip"; sha512 = "edb65dd0d7d1b9c40b2f50219aef30e116cedd6fc79290e740972c132c09106d2e80aa0bc8826673dd5a00222d4179c84b36a790eef63a4c4bca75a37ef90804"; };
"fast-levenshtein@npm:2.0.6" = { filename = "fast-levenshtein-npm-2.0.6-fcd74b8df5-92cfec0a8d.zip"; sha512 = "92cfec0a8dfafd9c7a15fba8f2cc29cd0b62b85f056d99ce448bbcd9f708e18ab2764bda4dd5158364f4145a7c72788538994f0d1787b956ef0d1062b0f7c24c"; };
"word-wrap@npm:1.2.3" = { filename = "word-wrap-npm-1.2.3-7fb15ab002-30b48f91fc.zip"; sha512 = "30b48f91fcf12106ed3186ae4fa86a6a1842416df425be7b60485de14bec665a54a68e4b5156647dec3a70f25e84d270ca8bc8cd23182ed095f5c7206a938c1f"; };
"fill-range@npm:7.0.1" = { filename = "fill-range-npm-7.0.1-b8b1817caa-cc283f4e65.zip"; sha512 = "cc283f4e65b504259e64fd969bcf4def4eb08d85565e906b7d36516e87819db52029a76b6363d0f02d0d532f0033c9603b9e2d943d56ee3b0d4f7ad3328ff917"; };
"has-flag@npm:4.0.0" = { filename = "has-flag-npm-4.0.0-32af9f0536-261a135703.zip"; sha512 = "261a1357037ead75e338156b1f9452c016a37dcd3283a972a30d9e4a87441ba372c8b81f818cd0fbcd9c0354b4ae7e18b9e1afa1971164aef6d18c2b6095a8ad"; };
"flatted@npm:3.2.7" = { filename = "flatted-npm-3.2.7-0da10b7c56-427633049d.zip"; sha512 = "427633049d55bdb80201c68f7eb1cbd533e03eac541f97d3aecab8c5526f12a20ccecaeede08b57503e772c769e7f8680b37e8d482d1e5f8d7e2194687f9ea35"; };
"callsites@npm:3.1.0" = { filename = "callsites-npm-3.1.0-268f989910-072d17b6ab.zip"; sha512 = "072d17b6abb459c2ba96598918b55868af677154bec7e73d222ef95a8fdb9bbf7dae96a8421085cdad8cd190d86653b5b6dc55a4484f2e5b2e27d5e0c3fc15b3"; };
"run-parallel@npm:1.2.0" = { filename = "run-parallel-npm-1.2.0-3f47ff2034-cb4f97ad25.zip"; sha512 = "cb4f97ad25a75ebc11a8ef4e33bb962f8af8516bb2001082ceabd8902e15b98f4b84b4f8a9b222e5d57fc3bd1379c483886ed4619367a7680dad65316993021d"; };
"reduce-flatten@npm:1.0.1" = { filename = "reduce-flatten-npm-1.0.1-63b2c5a753-5e5a450500.zip"; sha512 = "5e5a450500ece8dfff95ecd0b34f48941084c00fdc63e6a4413f758334d2d3f8b4d725670896c04853c477c062af03402aeb5e145b948e03abc914ee51bb3b89"; };
"color-convert@npm:2.0.1" = { filename = "color-convert-npm-2.0.1-79730e935b-79e6bdb9fd.zip"; sha512 = "79e6bdb9fd479a205c71d89574fccfb22bd9053bd98c6c4d870d65c132e5e904e6034978e55b43d69fcaa7433af2016ee203ce76eeba9cfa554b373e7f7db336"; };
"shebang-regex@npm:3.0.0" = { filename = "shebang-regex-npm-3.0.0-899a0cd65e-1a2bcae50d.zip"; sha512 = "1a2bcae50de99034fcd92ad4212d8e01eedf52c7ec7830eedcf886622804fe36884278f2be8be0ea5fde3fd1c23911643a4e0f726c8685b61871c8908af01222"; };
"isexe@npm:2.0.0" = { filename = "isexe-npm-2.0.0-b58870bd2e-26bf6c5480.zip"; sha512 = "26bf6c5480dda5161c820c5b5c751ae1e766c587b1f951ea3fcfc973bafb7831ae5b54a31a69bd670220e42e99ec154475025a468eae58ea262f813fdc8d1c62"; };
"rimraf@npm:3.0.2" = { filename = "rimraf-npm-3.0.2-2cb7dac69a-87f4164e39.zip"; sha512 = "87f4164e396f0171b0a3386cc1877a817f572148ee13a7e113b238e48e8a9f2f31d009a92ec38a591ff1567d9662c6b67fd8818a2dbbaed74bc26a87a2a4a9a0"; };
"is-callable@npm:1.2.7" = { filename = "is-callable-npm-1.2.7-808a303e61-61fd57d03b.zip"; sha512 = "61fd57d03b0d984e2ed3720fb1c7a897827ea174bd44402878e059542ea8c4aeedee0ea0985998aa5cc2736b2fa6e271c08587addb5b3959ac52cf665173d1ac"; };
"is-negative-zero@npm:2.0.2" = { filename = "is-negative-zero-npm-2.0.2-0adac91f15-f3232194c4.zip"; sha512 = "f3232194c47a549da60c3d509c9a09be442507616b69454716692e37ae9f37c4dea264fb208ad0c9f3efd15a796a46b79df07c7e53c6227c32170608b809149a"; };
"object-inspect@npm:1.12.2" = { filename = "object-inspect-npm-1.12.2-f125a822c0-a534fc1b85.zip"; sha512 = "a534fc1b8534284ed71f25ce3a496013b7ea030f3d1b77118f6b7b1713829262be9e6243acbcb3ef8c626e2b64186112cb7f6db74e37b2789b9c789ca23048b2"; };
"punycode@npm:2.1.1" = { filename = "punycode-npm-2.1.1-26eb3e15cf-823bf443c6.zip"; sha512 = "823bf443c6dd14f669984dea25757b37993f67e8d94698996064035edd43bed8a5a17a9f12e439c2b35df1078c6bec05a6c86e336209eb1061e8025c481168e8"; };
"is-shared-array-buffer@npm:1.0.2" = { filename = "is-shared-array-buffer-npm-1.0.2-32e4181fcd-9508929cf1.zip"; sha512 = "9508929cf14fdc1afc9d61d723c6e8d34f5e117f0bffda4d97e7a5d88c3a8681f633a74f8e3ad1fe92d5113f9b921dc5ca44356492079612f9a247efbce7032a"; };
"is-weakref@npm:1.0.2" = { filename = "is-weakref-npm-1.0.2-ff80e8c314-95bd9a57cd.zip"; sha512 = "95bd9a57cdcb58c63b1c401c60a474b0f45b94719c30f548c891860f051bc2231575c290a6b420c6bc6e7ed99459d424c652bd5bf9a1d5259505dc35b4bf83de"; };
"spdx-license-ids@npm:3.0.12" = { filename = "spdx-license-ids-npm-3.0.12-750216a0df-92a4dddce6.zip"; sha512 = "92a4dddce62ce1db6fe54a7a839cf85e06abc308fc83b776a55b44e4f1906f02e7ebd506120847039e976bbbad359ea8bdfafb7925eae5cd7e73255f02e0b7d6"; };
"spdx-exceptions@npm:2.3.0" = { filename = "spdx-exceptions-npm-2.3.0-2b68dad75a-cb69a26fa3.zip"; sha512 = "cb69a26fa3b46305637123cd37c85f75610e8c477b6476fa7354eb67c08128d159f1d36715f19be6f9daf4b680337deb8c65acdcae7f2608ba51931540687ac0"; };
"js-tokens@npm:4.0.0" = { filename = "js-tokens-npm-4.0.0-0ac852e9e2-8a95213a5a.zip"; sha512 = "8a95213a5a77deb6cbe94d86340e8d9ace2b93bc367790b260101d2f36a2eaf4e4e22d9fa9cf459b38af3a32fb4190e638024cf82ec95ef708680e405ea7cc78"; };
"get-symbol-description@npm:1.0.0" = { filename = "get-symbol-description-npm-1.0.0-9c95a4bc1f-9ceff8fe96.zip"; sha512 = "9ceff8fe968f9270a37a1f73bf3f1f7bda69ca80f4f80850670e0e7b9444ff99323f7ac52f96567f8b5f5fbe7ac717a0d81d3407c7313e82810c6199446a5247"; };
"is-regex@npm:1.1.4" = { filename = "is-regex-npm-1.1.4-cca193ef11-362399b335.zip"; sha512 = "362399b33535bc8f386d96c45c9feb04cf7f8b41c182f54174c1a45c9abbbe5e31290bbad09a458583ff6bf3b2048672cdb1881b13289569a7c548370856a652"; };
"queue-microtask@npm:1.2.3" = { filename = "queue-microtask-npm-1.2.3-fcc98e4e2d-b676f8c040.zip"; sha512 = "b676f8c040cdc5b12723ad2f91414d267605b26419d5c821ff03befa817ddd10e238d22b25d604920340fd73efd8ba795465a0377c4adf45a4a41e4234e42dc4"; };
"to-regex-range@npm:5.0.1" = { filename = "to-regex-range-npm-5.0.1-f1e8263b00-f76fa01b3d.zip"; sha512 = "f76fa01b3d5be85db6a2a143e24df9f60dd047d151062d0ba3df62953f2f697b16fe5dad9b0ac6191c7efc7b1d9dcaa4b768174b7b29da89d4428e64bc0a20ed"; };
"es-to-primitive@npm:1.2.1" = { filename = "es-to-primitive-npm-1.2.1-b7a7eac6c5-4ead6671a2.zip"; sha512 = "4ead6671a2c1402619bdd77f3503991232ca15e17e46222b0a41a5d81aebc8740a77822f5b3c965008e631153e9ef0580540007744521e72de8e33599fca2eed"; };
"internal-slot@npm:1.0.3" = { filename = "internal-slot-npm-1.0.3-9e05eea002-1944f92e98.zip"; sha512 = "1944f92e981e47aebc98a88ff0db579fd90543d937806104d0b96557b10c1f170c51fb777b97740a8b6ddeec585fca8c39ae99fd08a8e058dfc8ab70937238bf"; };
"regexp.prototype.flags@npm:1.4.3" = { filename = "regexp.prototype.flags-npm-1.4.3-df1c08b65d-51228bae73.zip"; sha512 = "51228bae732592adb3ededd5e15426be25f289e9c4ef15212f4da73f4ec3919b6140806374b8894036a86020d054a8d2657d3fee6bb9b4d35d8939c20030b7a6"; };
"safe-regex-test@npm:1.0.0" = { filename = "safe-regex-test-npm-1.0.0-e94a09b84e-bc566d8beb.zip"; sha512 = "bc566d8beb8b43c01b94e67de3f070fd2781685e835959bbbaaec91cc53381145ca91f69bd837ce6ec244817afa0a5e974fc4e40a2957f0aca68ac3add1ddd34"; };
"string.prototype.trimend@npm:1.0.5" = { filename = "string.prototype.trimend-npm-1.0.5-2b980efa37-d44f543833.zip"; sha512 = "d44f543833112f57224e79182debadc9f4f3bf9d48a0414d6f0cbd2a86f2b3e8c0ca1f95c3f8e5b32ae83e91554d79d932fc746b411895f03f93d89ed3dfb6bc"; };
"string.prototype.trimstart@npm:1.0.5" = { filename = "string.prototype.trimstart-npm-1.0.5-9e62187810-a4857c5399.zip"; sha512 = "a4857c5399ad709d159a77371eeaa8f9cc284469a0b5e1bfe405de16f1fd4166a8ea6f4180e55032f348d1b679b1599fd4301fbc7a8b72bdb3e795e43f7b1048"; };
"color-name@npm:1.1.4" = { filename = "color-name-npm-1.1.4-025792b0ea-b044585952.zip"; sha512 = "b0445859521eb4021cd0fb0cc1a75cecf67fceecae89b63f62b201cca8d345baf8b952c966862a9d9a2632987d4f6581f0ec8d957dfacece86f0a7919316f610"; };
"function.prototype.name@npm:1.1.5" = { filename = "function.prototype.name-npm-1.1.5-e776a642bb-acd21d733a.zip"; sha512 = "acd21d733a9b649c2c442f067567743214af5fa248dbeee69d8278ce7df3329ea5abac572be9f7470b4ec1cd4d8f1040e3c5caccf98ebf2bf861a0deab735c27"; };
"object.assign@npm:4.1.4" = { filename = "object.assign-npm-4.1.4-fb3deb1c3a-76cab513a5.zip"; sha512 = "76cab513a5999acbfe0ff355f15a6a125e71805fcf53de4e9d4e082e1989bdb81d1e329291e1e4e0ae7719f0e4ef80e88fb2d367ae60500d79d25a6224ac8864"; };
"unbox-primitive@npm:1.0.2" = { filename = "unbox-primitive-npm-1.0.2-cb56a05066-b7a1cf5862.zip"; sha512 = "b7a1cf5862b5e4b5deb091672ffa579aa274f648410009c81cca63fed3b62b610c4f3b773f912ce545bb4e31edc3138975b5bc777fc6e4817dca51affb6380e9"; };
"chalk@npm:2.4.2" = { filename = "chalk-npm-2.4.2-3ea16dd91e-ec3661d38f.zip"; sha512 = "ec3661d38fe77f681200f878edbd9448821924e0f93a9cefc0e26a33b145f1027a2084bf19967160d11e1f03bfe4eaffcabf5493b89098b2782c3fe0b03d80c2"; };
"is-number@npm:7.0.0" = { filename = "is-number-npm-7.0.0-060086935c-456ac6f8e0.zip"; sha512 = "456ac6f8e0f3111ed34668a624e45315201dff921e5ac181f8ec24923b99e9f32ca1a194912dc79d539c97d33dba17dc635202ff0b2cf98326f608323276d27a"; };
"functions-have-names@npm:1.2.3" = { filename = "functions-have-names-npm-1.2.3-e5cf1e2208-c3f1f5ba20.zip"; sha512 = "c3f1f5ba20f4e962efb71344ce0a40722163e85bee2101ce25f88214e78182d2d2476aa85ef37950c579eb6cf6ee811c17b3101bb84004bb75655f3e33f3fdb5"; };
"is-date-object@npm:1.0.5" = { filename = "is-date-object-npm-1.0.5-88f3d08b5e-baa9077cdf.zip"; sha512 = "baa9077cdf15eb7b58c79398604ca57379b2fc4cf9aa7a9b9e295278648f628c9b201400c01c5e0f7afae56507d741185730307cbe7cad3b9f90a77e5ee342fc"; };
"is-symbol@npm:1.0.4" = { filename = "is-symbol-npm-1.0.4-eb9baac703-92805812ef.zip"; sha512 = "92805812ef590738d9de49d677cd17dfd486794773fb6fa0032d16452af46e9b91bb43ffe82c983570f015b37136f4b53b28b8523bfb10b0ece7a66c31a54510"; };
"has-bigints@npm:1.0.2" = { filename = "has-bigints-npm-1.0.2-52732e614d-390e31e7be.zip"; sha512 = "390e31e7be7e5c6fe68b81babb73dfc35d413604d7ee5f56da101417027a4b4ce6a27e46eff97ad040c835b5d228676eae99a9b5c3bc0e23c8e81a49241ff45b"; };
"ansi-styles@npm:3.2.1" = { filename = "ansi-styles-npm-3.2.1-8cb8107983-d85ade01c1.zip"; sha512 = "d85ade01c10e5dd77b6c89f34ed7531da5830d2cb5882c645f330079975b716438cd7ebb81d0d6e6b4f9c577f19ae41ab55f07f19786b02f9dfd9e0377395665"; };
"supports-color@npm:5.5.0" = { filename = "supports-color-npm-5.5.0-183ac537bc-95f6f4ba5a.zip"; sha512 = "95f6f4ba5afdf92f495b5a912d4abee8dcba766ae719b975c56c084f5004845f6f5a5f7769f52d53f40e21952a6d87411bafe34af4a01e65f9926002e38e1dac"; };
"glob@npm:7.2.3" = { filename = "glob-npm-7.2.3-2d866d17a5-29452e97b3.zip"; sha512 = "29452e97b38fa704dabb1d1045350fb2467cf0277e155aa9ff7077e90ad81d1ea9d53d3ee63bd37c05b09a065e90f16aec4a65f5b8de401d1dac40bc5605d133"; };
"side-channel@npm:1.0.4" = { filename = "side-channel-npm-1.0.4-e1f38b9e06-351e41b947.zip"; sha512 = "351e41b947079c10bd0858364f32bb3a7379514c399edb64ab3dce683933483fc63fb5e4efe0a15a2e8a7e3c436b6a91736ddb8d8c6591b0460a24bb4a1ee245"; };
"which-boxed-primitive@npm:1.0.2" = { filename = "which-boxed-primitive-npm-1.0.2-e214f9ae5a-53ce774c73.zip"; sha512 = "53ce774c7379071729533922adcca47220228405e1895f26673bbd71bdf7fb09bee38c1d6399395927c6289476b5ae0629863427fd151491b71c4b6cb04f3a5e"; };
"has-flag@npm:3.0.0" = { filename = "has-flag-npm-3.0.0-16ac11fe05-4a15638b45.zip"; sha512 = "4a15638b454bf086c8148979aae044dd6e39d63904cd452d970374fa6a87623423da485dfb814e7be882e05c096a7ccf1ebd48e7e7501d0208d8384ff4dea73b"; };
"fs.realpath@npm:1.0.0" = { filename = "fs.realpath-npm-1.0.0-c8f05d8126-99ddea01a7.zip"; sha512 = "99ddea01a7e75aa276c250a04eedeffe5662bce66c65c07164ad6264f9de18fb21be9433ead460e54cff20e31721c811f4fb5d70591799df5f85dce6d6746fd0"; };
"path-is-absolute@npm:1.0.1" = { filename = "path-is-absolute-npm-1.0.1-31bc695ffd-060840f92c.zip"; sha512 = "060840f92cf8effa293bcc1bea81281bd7d363731d214cbe5c227df207c34cd727430f70c6037b5159c8a870b9157cba65e775446b0ab06fd5ecc7e54615a3b8"; };
"color-convert@npm:1.9.3" = { filename = "color-convert-npm-1.9.3-1fe690075e-fd7a64a17c.zip"; sha512 = "fd7a64a17cde98fb923b1dd05c5f2e6f7aefda1b60d67e8d449f9328b4e53b228a428fd38bfeaeb2db2ff6b6503a776a996150b80cdf224062af08a5c8a3a203"; };
"inflight@npm:1.0.6" = { filename = "inflight-npm-1.0.6-ccedb4b908-f4f76aa072.zip"; sha512 = "f4f76aa072ce19fae87ce1ef7d221e709afb59d445e05d47fba710e85470923a75de35bfae47da6de1b18afc3ce83d70facf44cfb0aff89f0a3f45c0a0244dfd"; };
"is-bigint@npm:1.0.4" = { filename = "is-bigint-npm-1.0.4-31c2eecbc9-c56edfe09b.zip"; sha512 = "c56edfe09b1154f8668e53ebe8252b6f185ee852a50f9b41e8d921cb2bed425652049fbe438723f6cb48a63ca1aa051e948e7e401e093477c99c84eba244f666"; };
"is-number-object@npm:1.0.7" = { filename = "is-number-object-npm-1.0.7-539d0e274d-d1e8d01bb0.zip"; sha512 = "d1e8d01bb0a7134c74649c4e62da0c6118a0bfc6771ea3c560914d52a627873e6920dd0fd0ebc0e12ad2ff4687eac4c308f7e80320b973b2c8a2c8f97a7524f7"; };
"color-name@npm:1.1.3" = { filename = "color-name-npm-1.1.3-728b7b5d39-09c5d3e33d.zip"; sha512 = "09c5d3e33d2105850153b14466501f2bfb30324a2f76568a408763a3b7433b0e50e5b4ab1947868e65cb101bb7cb75029553f2c333b6d4b8138a73fcc133d69d"; };
"is-boolean-object@npm:1.1.2" = { filename = "is-boolean-object-npm-1.1.2-ecbd575e6a-c03b23dbaa.zip"; sha512 = "c03b23dbaacadc18940defb12c1c0e3aaece7553ef58b162a0f6bba0c2a7e1551b59f365b91e00d2dbac0522392d576ef322628cb1d036a0fe51eb466db67222"; };
};

in optionalOverride overrideAttrs project
